const { getJestProjects } = require('@nx/jest');

export default {
  projects: [
    ...getJestProjects(),
    '<rootDir>/apps/mango',
    '<rootDir>/apps/mango-crem-features/accounting-profile/accounting-profiles',
    '<rootDir>/apps/mango-crem-features/accountmanagement/accounting-accountmanagement',
    '<rootDir>/apps/mango-crem-features/batch-accounting',
    '<rootDir>/apps/mango-crem-features/bookmarks',
    '<rootDir>/apps/mango-crem-features/central-auth',
    '<rootDir>/apps/mango-crem-features/central-authentication',
    '<rootDir>/apps/mango-crem-features/dashboards/portfolio-dashboard',
    '<rootDir>/apps/mango-crem-features/dashboards/project-dashboard',
    '<rootDir>/apps/mango-crem-features/envinfochip/env-info-chip',
    '<rootDir>/apps/mango-crem-features/group-maintenance',
    '<rootDir>/apps/mango-crem-features/list-pages',
    '<rootDir>/apps/mango-crem-features/nlas',
    '<rootDir>/apps/mango-crem-features/portfolio-maintenance',
    '<rootDir>/apps/mango-crem-features/reports',
    '<rootDir>/apps/mango-crem-features/start-page-selection',
    '<rootDir>/apps/mango-crem-features/user-maintenance',
    '<rootDir>/apps/mango/crem-features/central-auth',
    '<rootDir>/libs/core-shared',
    '<rootDir>/libs/data-models/lib-data-models',
    '<rootDir>/libs/ui-shared/cosmos',
    '<rootDir>/libs/ui-shared/lib-external-libraries',
    '<rootDir>/libs/ui-shared/lib-ui-elements',
    '<rootDir>/libs/ui-shared/lib-ui-shared',
    '<rootDir>/apps/mango-crem-features/alerts',
    '<rootDir>/apps/mango-crem-features/quick-search',
    '<rootDir>/apps/mango-crem-features/journal-entry-processing',
    '<rootDir>/libs/mango-nx-plugin',
    '<rootDir>/apps/mango-crem-features/object-actions',
    '<rootDir>/libs/forms-shared',
    '<rootDir>/apps/mango-crem-features/financial-reporting-settings',
    '<rootDir>/apps/mango-crem-features/data-set-dictionary',
  ],
};
