version: '3.7'

services:

  web:
    image: nginx:latest
    container_name: mango-app
    ports:
      - 8000:8000
    volumes:
      - ./Client/config/nginx-spa.conf:/etc/nginx/nginx.conf:ro
      - ./Client/dist/apps/mango:/usr/share/nginx/html
    restart: always

networks:
  frontend: