version: '3.9'

services:
  mango-spa:
    image: ${DOCKER_REGISTRY-}mango-spa
    container_name: mango-spa
    build:
      context: Client
      dockerfile: apps/mango/Dockerfile
    environment:
      - name=LOCAL
    ports:
      - 8084:8000
    restart: "no"
  
