import { Component, OnInit, ViewChild } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { DxSelectBoxComponent } from "devextreme-angular";

@Component({
	selector: 'client-select',
	templateUrl: './client-select.component.html',
	styleUrls: ['./client-select.component.scss']
})
export class ClientSelectComponent implements OnInit {

	@ViewChild("ClientList") clientList: DxSelectBoxComponent;

	clientOptions : string[] = [
		"10XGENOMICS", "24HOURFITNESS", "AAA", "AAANE", "AAP", "ABERCROMBIEANDFITCH", "ABM", "ABRHOLDINGS", "ACCO", "ACTIVISION", "ADECCOGROUP", "ADIDAS", "AECOM", "AGILENT", "AIRLIQUIDE", "AIRPRODUCTS", "AJG", "ALEXION", "ALLEGION", "ALLIANCEDATA", "ALNYLAM", "ALTICE", "AMERIPRISE", "AMSURG", "ANSYS", "ARAMARK", "ARAZZO", "ARCBEST", "ARLCAP", "ATLANTICHEALTH", "ATT", "AUTOCLUB", "AUTODESK", "BAREESCENTUALS", "BBT", "BBVACOMPASS", "BCBSFL", "BCBSM", "BECTONDICKINSON", "BFS", "BI-LO", "BIOGEN", "BJS", "BLUESTAR", "BNYM", "BOOTBARN", "BRAMBLES", "BRIGHTHORIZONS", "BROADCOM", "BROOKDALE", "BSC", "BUFFALOEXCHANGE", "BURBERRY", "CALIBER", "CAMPERO", "CAPGEMINI", "CARDINALHEALTH", "CARMAX", "CARTERS", "CBK", "CBRE", "CBRE2", "CBRECORP", "CBREGCS", "CELGENE", "CENTENE", "CENTURYLINK", "CHARLESRIVER", "CHEVRON", "CHOA", "CHR", "CHS", "CHUYS", "CITI", "CITILA", "CMG", "COCACOLA", "COGNIZANT", "CONFIESEGUROS", "CONFLUENT", "CORELOGIC", "CORTEVA", "COSTAR", "COSTCO", "COX", "CRANE", "CRESABOSTON", "CROWN", "CSLPLASMA", "CSTRAIN", "CTWEST", "CUSHMAN", "CUSHWAKE", "CUSHWAKERETAIL", "CWAPAC", "CWBALTIMORE", "CWBOSTON", "CWCincinnati", "CWEMEA", "CWIBM", "CWNRETAIL", "CWSTANDARD", "DANAHER", "DAVITA", "DBS", "DEANFOODS", "DENNYS", "DFA", "DHL", "DIRECTGENERAL", "DOLE", "DUNKIN", "DUPONT", "DYCOM", "EDELMAN", "EIS", "EMCOR", "ENTERGY", "ENVISTA", "EPLUS", "EXPEDITORS", "FACEBOOK", "FCB", "FIDELITY", "FIFTHTHIRD", "FIFTHTHIRDLA", "FIVEGUYS", "FLAGSHIP", "FLIR", "FLUOR", "FOA", "FORTIVE", "FRGI", "FROSTBANK", "FSH", "GALARDI", "GBRX", "GCG", "Genworth", "GHC", "GLOBALPARTNERS", "GODIVA", "GOLDER", "GOODYEAR", "GP", "GRIFFON", "GT", "GUESS", "GUIDEWIRE", "GYMBOREE", "HANGER", "HARTFORD", "HAVERTYS", "HDSUPPLY", "Hibbett", "HITACHIVANTARA", "HOLOGIC", "HOSPITALITY", "HPE", "IAAI", "IBERIABANK", "IBM", "IFF", "INSPIREBRANDS", "INTUIT", "IO", "IPP", "IR", "ITOCHU", "JAB", "JLL", "JLLLAS", "JPMC", "KAH", "KANTAR", "KARAUCTION", "KC", "KEURIGDRPEPPER", "KEYBANK", "KEYSIGHT", "KINDRED", "KIRKLANDS", "KOCH", "LANDOLAKES", "LEASEACCOUNTING", "LEASEMANAGER", "LeaseServices", "LEGACYHEALTH", "LENNOX", "LIVENATION", "LOANDEPOT", "LOGANSROADHOUSE", "LVHN", "LWH", "MAGNA", "MANPOWER", "MARKEL", "MASTERCARD", "MAVERICKLTS", "MAXIMUS", "MCCALLALMY", "MCJUNKINREDMAN", "MERITOR", "MICHAELKORS", "MIDAS", "MOHAWK", "MOOG", "MOTOROLA", "MUFG", "MYLAN", "NAB", "NAPA", "NCPARTNERS", "NCR", "NEWCO", "NEWMARK", "NLOK", "NORTHMARQ", "OMNICOM", "OPENTEXT", "ORBITALATK", "OSHKOSH", "OTIS", "OWENSCORNING", "PANASONIC", "PARKERHANNIFIN", "PARPACIFIC", "PARTSAUTHORITY", "PEPSI", "PERRIGO", "POLO", "POTBELLY", "PRATT", "PRICELINE", "Production2", "PROGRESSIVE", "PROTIVITI", "PROVENTURE", "PROVIDENCE", "PSG", "PUB", "PVH", "PWC", "QUALA", "QUEST", "RABOBANK", "RAGANDBONE", "RBC", "RBI", "RCN", "REALMEX", "REALOGY", "REDHAT", "REGENERON", "REGIONS", "REI", "RESCARE", "RESMED", "RESTORATIONHARDWARE", "RETAILDEMO", "RGHL", "RGP", "RIGOR1", "RIGOR2", "RIGOR3", "RIGOR4", "RIGOR5", "ROCKWELLAUTOMATION", "ROLLS-ROYCE", "ROSS", "RUTHS", "RYDER", "SALTCHUK", "SelectComfort", "SENTARA", "SERVICEEXPERTS", "SERVICEMASTER", "Shopko", "SITEONE", "SNEAKERVILLA", "SONY", "SOUTHERNCO", "SPC", "SPGLOBAL", "SPINUPCW1", "SPINUPCW2", "STANTEC", "STATESTREET", "STERIS", "STUDLEY1", "SUNSTATE", "SUTTERHEALTH", "SWN", "SYNEOS", "SYNOVUS", "TBC", "TCP", "Texasroadhouse", "TMOBILE", "TNT", "TOTALWINE", "TRAIN", "TUESDAYMORNING", "TUMI", "UBER", "UBSH", "UHHOSPITALS", "UNDERARMOUR", "UNIVAR", "UPENN", "UPITT", "UPS", "USAA", "USBank", "USCONCRETE", "USFOODS", "USLBM", "UVMHEALTH", "VALVOLINE", "VARIANMEDICAL", "VERITAS", "VERITIV", "VIAD", "VISA", "WESTPAC", "WESTROCK", "WORLDACCEPTANCE", "WPP", "WWINTL", "WYNDHAM", "WYNDHAMHOTELS", "XYLEM", "ZEBRA", "ZUMIEZ"
	];

	recentClients : string[] = [
		"24HOURFITNESS", "ABERCROMBIEANDFITCH", "BLANK", "FAF", "JPMC", "RETAILDEMO", "VZW", "WESTERNUNION", "ZUMIEZ"
	];

	constructor( private route: ActivatedRoute, private router: Router ) { 
	}

	ngOnInit() {		
	}

	ngAfterViewInit() {
		this.clientList.instance.focus();
	}

	goToClientsite() {
		this.router.navigate(['start-page']);
	}

}


