import { DashboardConfig } from '@mango/data-models/lib-data-models';

export const dashboardIFRSAnnually: DashboardConfig = {
  dashboardId: 6,
  pendoId: 'IFRSAnnualDisclosures',
  localCardConfig: [
    {
      index: 0,
      id: 'IFRS16-Annual-Lease-Counts',
      name: 'Lease Counts',
      sortingOrder: {
        'Opening Lease Count': 1,
        '- Leases Added': 2,
        '- Leases Expired/Cancelled': 3,
        'Closing Lease Count': 4,
      },
      format: {
        type: 'fixedPoint',
        precision: 0,
      },
      sortedColumnFieldName: 'LeaseTemplate',
      columnSortingOrder: {
        Lease: 1,
        'JE Lease': 2,
        'Real Estate Lease': 3,
        'Equipment Lease': 4,
        'Office Equipment Lease': 5,
        Total: 10,
      },
      fieldTransform: [
        {
          LeaseTemplate: 'LeaseTemplate',
          Display: 'Opening Lease Count',
          PeriodYear: 'PeriodYear',
          data: 'OpeningCount',
        },
        {
          LeaseTemplate: 'LeaseTemplate',
          Display: '- Leases Added',
          PeriodYear: 'PeriodYear',
          data: 'AddedCount',
        },
        {
          LeaseTemplate: 'LeaseTemplate',
          Display: '- Leases Expired/Cancelled',
          PeriodYear: 'PeriodYear',
          data: 'EndedCount',
        },
        {
          LeaseTemplate: 'LeaseTemplate',
          Display: 'Closing Lease Count',
          PeriodYear: 'PeriodYear',
          data: 'ClosingCount',
        },
        // Totals
        {
          LeaseTemplate: 'Total',
          Display: 'Opening Lease Count',
          PeriodYear: 'PeriodYear',
          data: 'OpeningCount',
        },
        {
          LeaseTemplate: 'Total',
          Display: '- Leases Added',
          PeriodYear: 'PeriodYear',
          data: 'AddedCount',
        },
        {
          LeaseTemplate: 'Total',
          Display: '- Leases Expired/Cancelled',
          PeriodYear: 'PeriodYear',
          data: 'EndedCount',
        },
        {
          LeaseTemplate: 'Total',
          Display: 'Closing Lease Count',
          PeriodYear: 'PeriodYear',
          data: 'ClosingCount',
        },
      ],
    },
    {
      index: 1,
      id: 'IFRS16-Annual-Asset-Balance',
      name: 'Assets and Liabilities Balances',
      width: 200,
      sortingOrder: {
        'ROU Asset Balance - Opening': 1,
        'ROU Asset Balance - Added': 2,
        'ROU Asset Balance - Amortization': 3,
        'ROU Asset Balance - Adjustment': 4,
        'ROU Asset Balance - Closing': 5,

        'Short Term Liability Balance': 6,
        'Long Term Liability Balance': 7,
        'Total Liability Balance': 8,
      },
      sortedColumnFieldName: 'LeaseTemplate',
      columnSortingOrder: {
        Lease: 1,
        'JE Lease': 2,
        'Real Estate Lease': 3,
        'Equipment Lease': 4,
        'Office Equipment Lease': 5,
        Total: 10,
      },
      fieldTransform: [
        // First Part
        {
          LeaseTemplate: 'LeaseTemplate',
          Display: 'ROU Asset Balance - Opening',
          PeriodYear: 'PeriodYear',
          data: 'AssetBalanceOpeningReporting',
        },
        {
          LeaseTemplate: 'LeaseTemplate',
          Display: 'ROU Asset Balance - Added',
          PeriodYear: 'PeriodYear',
          data: 'AssetBalanceAddedReporting',
        },
        {
          LeaseTemplate: 'LeaseTemplate',
          Display: 'ROU Asset Balance - Amortization',
          PeriodYear: 'PeriodYear',
          data: 'AssetBalanceAmortizationReporting',
        },
        {
          LeaseTemplate: 'LeaseTemplate',
          Display: 'ROU Asset Balance - Adjustment',
          PeriodYear: 'PeriodYear',
          data: 'AssetBalanceAdjustmentReporting',
        },
        {
          LeaseTemplate: 'LeaseTemplate',
          Display: 'ROU Asset Balance - Closing',
          PeriodYear: 'PeriodYear',
          data: 'AssetBalanceClosingReporting',
        },
        // Second Part
        {
          LeaseTemplate: 'LeaseTemplate',
          Display: 'Short Term Liability Balance',
          PeriodYear: 'PeriodYear',
          data: 'ShortTermLiabilityClosingReporting',
        },
        {
          LeaseTemplate: 'LeaseTemplate',
          Display: 'Long Term Liability Balance',
          PeriodYear: 'PeriodYear',
          data: 'LongTermLiabilityClosingReporting',
        },
        {
          LeaseTemplate: 'LeaseTemplate',
          Display: 'Total Liability Balance',
          PeriodYear: 'PeriodYear',
          data: 'LiabilityBalanceClosingReporting',
        },
        // Totals
        // First Part
        {
          LeaseTemplate: 'Total',
          Display: 'ROU Asset Balance - Opening',
          PeriodYear: 'PeriodYear',
          data: 'AssetBalanceOpeningReporting',
        },
        {
          LeaseTemplate: 'Total',
          Display: 'ROU Asset Balance - Added',
          PeriodYear: 'PeriodYear',
          data: 'AssetBalanceAddedReporting',
        },
        {
          LeaseTemplate: 'Total',
          Display: 'ROU Asset Balance - Amortization',
          PeriodYear: 'PeriodYear',
          data: 'AssetBalanceAmortizationReporting',
        },
        {
          LeaseTemplate: 'Total',
          Display: 'ROU Asset Balance - Adjustment',
          PeriodYear: 'PeriodYear',
          data: 'AssetBalanceAdjustmentReporting',
        },
        {
          LeaseTemplate: 'Total',
          Display: 'ROU Asset Balance - Closing',
          PeriodYear: 'PeriodYear',
          data: 'AssetBalanceClosingReporting',
        },
        {
          LeaseTemplate: 'Total',
          Display: 'Short Term Liability Balance',
          PeriodYear: 'PeriodYear',
          data: 'ShortTermLiabilityClosingReporting',
        },
        {
          LeaseTemplate: 'Total',
          Display: 'Long Term Liability Balance',
          PeriodYear: 'PeriodYear',
          data: 'LongTermLiabilityClosingReporting',
        },
        {
          LeaseTemplate: 'Total',
          Display: 'Total Liability Balance',
          PeriodYear: 'PeriodYear',
          data: 'LiabilityBalanceClosingReporting',
        },
      ],
    },
    {
      index: 2,
      name: 'Lease Costs',
      id: 'IFRS16-Annual-Lease-Cost',
      width: 200,
      showRowGrandTotals: true,
      texts: {
        grandTotal: 'Total Lease Cost',
      },
      combineWithIndex: 3,
      sortingOrder: {
        'Finance Lease Cost': 0,
        '- Depreciation of right-of-use Assets': 1,
        '- Interest on Lease Liabilities': 2,
        'Reporting Exceptions Cost Short-Term Leases': 3,
        'Reporting Exceptions Cost Low-Value Leases': 4,
        'Other Reporting Exceptions': 5,
        'Variable Lease Cost': 6,
        'Variable Cost of Indexed Payments': 7,
        'Sublease Income': 8,
        'Total Lease Cost': 9,
      },
      sortedColumnFieldName: 'LeaseTemplate',
      columnSortingOrder: {
        Lease: 1,
        'JE Lease': 2,
        'Real Estate Lease': 3,
        'Equipment Lease': 4,
        'Office Equipment Lease': 5,
        Total: 10,
      },
      fieldTransform: [
        {
          LeaseTemplate: 'LeaseTemplate',
          Display: 'Finance Lease Cost',
          PeriodYear: 'PeriodYear',
          data: 'FinanceLeaseCostReporting',
        },
        {
          LeaseTemplate: 'LeaseTemplate',
          Display: '- Depreciation of right-of-use Assets',
          PeriodYear: 'PeriodYear',
          data: 'DepreciationOfROUAssets',
        },
        {
          LeaseTemplate: 'LeaseTemplate',
          Display: '- Interest on Lease Liabilities',
          PeriodYear: 'PeriodYear',
          data: 'LeaseLiabilityInterestReporting',
        },
        {
          LeaseTemplate: 'LeaseTemplate',
          Display: 'Reporting Exceptions Cost Short-Term Leases',
          PeriodYear: 'PeriodYear',
          data: 'ShortTermLeaseReportingExceptionCostReporting',
        },
        {
          LeaseTemplate: 'LeaseTemplate',
          Display: 'Reporting Exceptions Cost Low-Value Leases',
          PeriodYear: 'PeriodYear',
          data: 'LowValueLeaseReportingExceptionCostReporting',
        },
        {
          LeaseTemplate: 'LeaseTemplate',
          Display: 'Other Reporting Exceptions',
          PeriodYear: 'PeriodYear',
          data: 'OtherReportingExceptionCostReporting',
        },
        {
          LeaseTemplate: 'LeaseTemplate',
          Display: 'Variable Lease Cost',
          PeriodYear: 'PeriodYear',
          data: 'VariableLeaseCostReporting',
        },
        {
          LeaseTemplate: 'LeaseTemplate',
          Display: 'Variable Cost of Indexed Payments',
          PeriodYear: 'PeriodYear',
          data: 'VariableLeaseCostOfIndexedPaymentsReporting',
        },
        {
          LeaseTemplate: 'LeaseTemplate',
          Display: 'Sublease Income',
          PeriodYear: 'PeriodYear',
          data: 'SubleaseIncome',
        },
        {
          LeaseTemplate: 'Total',
          Display: 'Finance Lease Cost',
          PeriodYear: 'PeriodYear',
          data: 'FinanceLeaseCostReporting',
        },
        {
          LeaseTemplate: 'Total',
          Display: '- Depreciation of right-of-use Assets',
          PeriodYear: 'PeriodYear',
          data: 'DepreciationOfROUAssets',
        },
        {
          LeaseTemplate: 'Total',
          Display: '- Interest on Lease Liabilities',
          PeriodYear: 'PeriodYear',
          data: 'LeaseLiabilityInterestReporting',
        },
        {
          LeaseTemplate: 'Total',
          Display: 'Reporting Exceptions Cost Short-Term Leases',
          PeriodYear: 'PeriodYear',
          data: 'ShortTermLeaseReportingExceptionCostReporting',
        },
        {
          LeaseTemplate: 'Total',
          Display: 'Reporting Exceptions Cost Low-Value Leases',
          PeriodYear: 'PeriodYear',
          data: 'LowValueLeaseReportingExceptionCostReporting',
        },
        {
          LeaseTemplate: 'Total',
          Display: 'Other Reporting Exceptions',
          PeriodYear: 'PeriodYear',
          data: 'OtherReportingExceptionCostReporting',
        },
        {
          LeaseTemplate: 'Total',
          Display: 'Variable Lease Cost',
          PeriodYear: 'PeriodYear',
          data: 'VariableLeaseCostReporting',
        },
        {
          LeaseTemplate: 'Total',
          Display: 'Variable Cost of Indexed Payments',
          PeriodYear: 'PeriodYear',
          data: 'VariableLeaseCostOfIndexedPaymentsReporting',
        },
        {
          LeaseTemplate: 'Total',
          Display: 'Sublease Income',
          PeriodYear: 'PeriodYear',
          data: 'SubleaseIncome',
        },
      ],
    },
    {
      index: 3,
      name: 'Reporting Exceptions Cost',
      id: 'IFRS16-Annual-Reporting-Exceptions-Cost',
      width: 200,
      sortingOrder: {
        'ST Lease & Reporting Exceptions Cost - Cash Basis': 0,
        'ST Lease & Reporting Exceptions Cost - SL Accrual Basis': 0,
      },
      sortedColumnFieldName: 'LeaseTemplate',
      columnSortingOrder: {
        Lease: 1,
        'JE Lease': 2,
        'Real Estate Lease': 3,
        'Equipment Lease': 4,
        'Office Equipment Lease': 5,
        Total: 10,
      },
      fieldTransform: [
        {
          LeaseTemplate: 'LeaseTemplate',
          Display: 'ST Lease & Reporting Exceptions Cost - Cash Basis',
          PeriodYear: 'PeriodYear',
          data: 'ShortTermLeaseAndReportingExceptionCostCashBasisReporting',
        },
        {
          LeaseTemplate: 'LeaseTemplate',
          Display: 'ST Lease & Reporting Exceptions Cost - SL Accrual Basis',
          PeriodYear: 'PeriodYear',
          data: 'ShortTermLeaseAndReportingExceptionCostAccrualBasisReporting',
        },
        {
          LeaseTemplate: 'Total',
          Display: 'ST Lease & Reporting Exceptions Cost - Cash Basis',
          PeriodYear: 'PeriodYear',
          data: 'ShortTermLeaseAndReportingExceptionCostCashBasisReporting',
        },
        {
          LeaseTemplate: 'Total',
          Display: 'ST Lease & Reporting Exceptions Cost - SL Accrual Basis',
          PeriodYear: 'PeriodYear',
          data: 'ShortTermLeaseAndReportingExceptionCostAccrualBasisReporting',
        },
      ],
    },
    {
      index: 4,
      name: 'Other Information',
      id: 'IFRS16-Annual-Other-Information',
      width: 200,
      sortingOrder: {
        'Cash Flows - Total': 0,
        'Cash Flows - Interest': 1,
        'Cash Flows - Principal Repayment': 2,
        'Right-of-use Assets Obtained In Exchange For New Finance Liabilities': 3,
        'Weighted-Average Remaining Years to Accounting Term': 4,
        'Weighted-Average Remaining Years to Expiration': 5,
        'Weighted-Average Incremental Borrowing Rate': 6,
      },
      sortedColumnFieldName: 'LeaseTemplate',
      columnSortingOrder: {
        Lease: 1,
        'JE Lease': 2,
        'Real Estate Lease': 3,
        'Equipment Lease': 4,
        'Office Equipment Lease': 5,
        Total: 10,
      },
      fieldTransform: [
        {
          LeaseTemplate: 'LeaseTemplate',
          Display: 'Cash Flows - Total',
          PeriodYear: 'PeriodYear',
          data: 'CashFlowsTotalReporting',
        },
        {
          LeaseTemplate: 'LeaseTemplate',
          Display: 'Cash Flows - Interest',
          PeriodYear: 'PeriodYear',
          data: 'CashFlowsInterestReporting',
        },
        {
          LeaseTemplate: 'LeaseTemplate',
          Display: 'Cash Flows - Principal Repayment',
          PeriodYear: 'PeriodYear',
          data: 'CashFlowsPrincipalRepaymentReporting',
        },
        {
          LeaseTemplate: 'LeaseTemplate',
          Display:
            'Right-of-use Assets Obtained In Exchange For New Finance Liabilities',
          PeriodYear: 'PeriodYear',
          data: 'ROUAssetsObtainedInExchangeForNewFinanceLiabilities',
        },
        {
          LeaseTemplate: 'LeaseTemplate',
          Display: 'Weighted-Average Remaining Years to Accounting Term',
          PeriodYear: 'PeriodYear',
          data: 'WeightedAverageYearsRemainingToAccountingTermFinance',
        },
        {
          LeaseTemplate: 'LeaseTemplate',
          Display: 'Weighted-Average Remaining Years to Expiration',
          PeriodYear: 'PeriodYear',
          data: 'WeightedAverageYearsRemainingToExpirationFinance',
        },
        {
          LeaseTemplate: 'LeaseTemplate',
          Display: 'Weighted-Average Incremental Borrowing Rate',
          PeriodYear: 'PeriodYear',
          data: 'WeightedAverageIncrementalBorrowingRate',
        },
        // Totals
        {
          LeaseTemplate: 'Total',
          Display: 'Cash Flows - Total',
          PeriodYear: 'PeriodYear',
          data: 'CashFlowsTotalReporting',
        },
        {
          LeaseTemplate: 'Total',
          Display: 'Cash Flows - Interest',
          PeriodYear: 'PeriodYear',
          data: 'CashFlowsInterestReporting',
        },
        {
          LeaseTemplate: 'Total',
          Display: 'Cash Flows - Principal Repayment',
          PeriodYear: 'PeriodYear',
          data: 'CashFlowsPrincipalRepaymentReporting',
        },
        {
          LeaseTemplate: 'Total',
          Display:
            'Right-of-use Assets Obtained In Exchange For New Finance Liabilities',
          PeriodYear: 'PeriodYear',
          data: 'ROUAssetsObtainedInExchangeForNewFinanceLiabilities',
        },
        {
          LeaseTemplate: 'Total',
          Display: 'Weighted-Average Remaining Years to Accounting Term',
          PeriodYear: 'PeriodYear',
          data: 'WeightedAverageYearsRemainingToAccountingTermFinance',
        },
        {
          LeaseTemplate: 'Total',
          Display: 'Weighted-Average Remaining Years to Expiration',
          PeriodYear: 'PeriodYear',
          data: 'WeightedAverageYearsRemainingToExpirationFinance',
        },
        {
          LeaseTemplate: 'Total',
          Display: 'Weighted-Average Incremental Borrowing Rate',
          PeriodYear: 'PeriodYear',
          data: 'WeightedAverageIncrementalBorrowingRate',
        },
      ],
    },
    {
      index: 5,
      name: 'Liability Maturity',
      id: 'IFRS16-Annual-Liability-Maturity',
      filterData: [
        { displayKey: '5 years', valueKey: 6 },
        { displayKey: '10 years', valueKey: 11 },
      ],
      filterBy: 'PeriodYear',
      filterInitialValue: { displayKey: '5 years', valueKey: 6 },
      width: 200,
      sortingOrder: {
        Thereafter: 100,
      },
      sortedColumnFieldName: 'LeaseTemplate',
      columnSortingOrder: {
        Lease: 1,
        'JE Lease': 2,
        'Real Estate Lease': 3,
        'Equipment Lease': 4,
        'Office Equipment Lease': 5,
        Total: 10,
      },
      fieldTransform: [
        {
          LeaseTemplate: 'LeaseTemplate',
          PeriodYear: 'PeriodYear',
          data: 'ScheduledPaymentsReporting',
          modify: {
            replace: 'ScheduledPaymentsReporting',
            newData: 'RemainingPaymentsReporting',
            compareWith: 'PeriodYear',
            compareWithX: 'LeaseTemplate',
            offset: -1,
            indexes: 'last',
            caption: 'Thereafter',
          },
        },
        {
          LeaseTemplate: 'Total',
          PeriodYear: 'PeriodYear',
          data: 'ScheduledPaymentsReporting',
          modify: {
            replace: 'ScheduledPaymentsReporting',
            newData: 'RemainingPaymentsReporting',
            compareWith: 'PeriodYear',
            compareWithX: 'LeaseTemplate',
            offset: -1,
            indexes: 'last',
            caption: 'Thereafter',
          },
        },
      ],
    },
    {
      index: 6,
      name: 'Reconciliation of Lease Liabilities',
      id: 'IFRS16-Annual-Reconciliation-of-Lease-Liabilities',
      width: 200,
      sortingOrder: {
        'Weighted-Average Remaining Years to Accounting Term': 0,
        'Weighted-Average Remaining Years to Expiration': 1,
        'Weighted-Average Incremental Borrowing Rate': 2,
        'Total Undiscounted Lease Liability': 3,
        'Imputed Interest': 4,
        'Total Discounted Lease Liability': 5,
      },
      sortedColumnFieldName: 'LeaseTemplate',
      columnSortingOrder: {
        Lease: 1,
        'JE Lease': 2,
        'Real Estate Lease': 3,
        'Equipment Lease': 4,
        'Office Equipment Lease': 5,
        Total: 10,
      },
      texts: {
        grandTotal: 'Total',
      },
      showColumnGrandTotals: true,
      fieldTransform: [
        {
          LeaseTemplate: 'LeaseTemplate',
          Display: 'Weighted-Average Remaining Years to Accounting Term',
          data: 'WeightedAverageYearsRemainingToAccountingTerm',
        },
        {
          LeaseTemplate: 'LeaseTemplate',
          Display: 'Weighted-Average Remaining Years to Expiration',
          data: 'WeightedAverageYearsRemainingToExpiration',
        },
        {
          LeaseTemplate: 'LeaseTemplate',
          Display: 'Weighted-Average Incremental Borrowing Rate',
          data: 'WeightedAverageDiscountRate',
        },
        {
          LeaseTemplate: 'LeaseTemplate',
          Display: 'Total Undiscounted Lease Liability',
          data: 'TotalUndiscountedLeaseLiability',
        },
        {
          LeaseTemplate: 'LeaseTemplate',
          Display: 'Imputed Interest',
          data: 'ImputedInterest',
        },
        {
          LeaseTemplate: 'LeaseTemplate',
          Display: 'Total Discounted Lease Liability',
          data: 'TotalDiscountedLeaseLiability',
        },
      ],
    },
    {
      index: 7,
      name: 'Future Commitments',
      id: 'IFRS16-Annual-Future-Commitments',
      width: 200,
      sortingOrder: {},
      sortedColumnFieldName: 'LeaseTemplate',
      columnSortingOrder: {
        Lease: 1,
        'JE Lease': 2,
        'Real Estate Lease': 3,
        'Equipment Lease': 4,
        'Office Equipment Lease': 5,
        Total: 10,
      },
      filterData: [
        { displayKey: '5 years', valueKey: 6 },
        { displayKey: '10 years', valueKey: 11 },
      ],
      filterBy: 'PeriodYear',
      filterInitialValue: { displayKey: '5 years', valueKey: 6 },
      fieldTransform: [
        {
          LeaseTemplate: 'LeaseTemplate',
          PeriodYear: 'PeriodYear',
          data: 'ScheduledPaymentsReporting',
          modify: {
            replace: 'ScheduledPaymentsReporting',
            newData: 'RemainingPaymentsReporting',
            compareWith: 'PeriodYear',
            offset: -1,
            indexes: 'last',
            caption: 'Thereafter',
          },
        },
        {
          LeaseTemplate: 'Total',
          PeriodYear: 'PeriodYear',
          data: 'ScheduledPaymentsReporting',
          modify: {
            replace: 'ScheduledPaymentsReporting',
            newData: 'RemainingPaymentsReporting',
            compareWith: 'PeriodYear',
            offset: -1,
            indexes: 'last',
            caption: 'Thereafter',
          },
        },
      ],
    },
  ],
};

export const dashboardIFRSQuarterly: DashboardConfig = {
  dashboardId: 7,
  pendoId: 'IFRSQuarterlyDisclosures',
  localCardConfig: [
    {
      index: 0,
      id: 'IFRS16-Quarterly-Lease-Counts',
      name: 'Lease Counts',
      format: {
        type: 'fixedPoint',
        precision: 0,
      },
      sortingOrder: {
        'Opening Lease Count': 1,
        '- Leases Added': 2,
        '- Leases Expired/Cancelled': 3,
        'Closing Lease Count': 4,
      },
      sortedColumnFieldName: 'LeaseTemplate',
      columnSortingOrder: {
        'Real Estate Lease': 1,
        'Equipment Lease': 2,
        'Office Equipment Lease': 3,
        Total: 4,
      },
      fieldTransform: [
        {
          LeaseTemplate: 'LeaseTemplate',
          Display: 'Opening Lease Count',
          PeriodQuarter: 'PeriodQuarter',
          data: 'OpeningCount',
        },
        {
          LeaseTemplate: 'LeaseTemplate',
          Display: '- Leases Added',
          PeriodQuarter: 'PeriodQuarter',
          data: 'AddedCount',
        },
        {
          LeaseTemplate: 'LeaseTemplate',
          Display: '- Leases Expired/Cancelled',
          PeriodQuarter: 'PeriodQuarter',
          data: 'EndedCount',
        },
        {
          LeaseTemplate: 'LeaseTemplate',
          Display: 'Closing Lease Count',
          PeriodQuarter: 'PeriodQuarter',
          data: 'ClosingCount',
        },
        // Totals
        {
          LeaseTemplate: 'Total',
          Display: 'Opening Lease Count',
          PeriodQuarter: 'PeriodQuarter',
          data: 'OpeningCount',
        },
        {
          LeaseTemplate: 'Total',
          Display: '- Leases Added',
          PeriodQuarter: 'PeriodQuarter',
          data: 'AddedCount',
        },
        {
          LeaseTemplate: 'Total',
          Display: '- Leases Expired/Cancelled',
          PeriodQuarter: 'PeriodQuarter',
          data: 'EndedCount',
        },
        {
          LeaseTemplate: 'Total',
          Display: 'Closing Lease Count',
          PeriodQuarter: 'PeriodQuarter',
          data: 'ClosingCount',
        },
      ],
    },
    {
      index: 1,
      id: 'IFRS16-Quarterly-Asset-Balance',
      name: 'Assets and Liabilities Balances',
      width: 200,
      sortingOrder: {
        'ROU Asset Balance - Opening': 1,
        'ROU Asset Balance - Added': 2,
        'ROU Asset Balance - Amortization': 3,
        'ROU Asset Balance - Adjustment': 4,
        'ROU Asset Balance - Closing': 5,

        'Short Term Liability Balance': 6,
        'Long Term Liability Balance': 7,
        'Total Liability Balance': 8,
      },
      sortedColumnFieldName: 'LeaseTemplate',
      columnSortingOrder: {
        'Real Estate Lease': 1,
        'Equipment Lease': 2,
        'Office Equipment Lease': 3,
        Total: 4,
      },
      fieldTransform: [
        // First Part
        {
          LeaseTemplate: 'LeaseTemplate',
          Display: 'ROU Asset Balance - Opening',
          PeriodQuarter: 'PeriodQuarter',
          data: 'AssetBalanceOpeningReporting',
        },
        {
          LeaseTemplate: 'LeaseTemplate',
          Display: 'ROU Asset Balance - Added',
          PeriodQuarter: 'PeriodQuarter',
          data: 'AssetBalanceAddedReporting',
        },
        {
          LeaseTemplate: 'LeaseTemplate',
          Display: 'ROU Asset Balance - Amortization',
          PeriodQuarter: 'PeriodQuarter',
          data: 'AssetBalanceAmortizationReporting',
        },
        {
          LeaseTemplate: 'LeaseTemplate',
          Display: 'ROU Asset Balance - Adjustment',
          PeriodQuarter: 'PeriodQuarter',
          data: 'AssetBalanceAdjustmentReporting',
        },
        {
          LeaseTemplate: 'LeaseTemplate',
          Display: 'ROU Asset Balance - Closing',
          PeriodQuarter: 'PeriodQuarter',
          data: 'AssetBalanceClosingReporting',
        },
        // Second Part
        {
          LeaseTemplate: 'LeaseTemplate',
          Display: 'Short Term Liability Balance',
          PeriodQuarter: 'PeriodQuarter',
          data: 'ShortTermLiabilityClosingReporting',
        },
        {
          LeaseTemplate: 'LeaseTemplate',
          Display: 'Long Term Liability Balance',
          PeriodQuarter: 'PeriodQuarter',
          data: 'LongTermLiabilityClosingReporting',
        },
        {
          LeaseTemplate: 'LeaseTemplate',
          Display: 'Total Liability Balance',
          PeriodQuarter: 'PeriodQuarter',
          data: 'LiabilityBalanceClosingReporting',
        },
        // Totals
        // First Part
        {
          LeaseTemplate: 'Total',
          Display: 'ROU Asset Balance - Opening',
          PeriodQuarter: 'PeriodQuarter',
          data: 'AssetBalanceOpeningReporting',
        },
        {
          LeaseTemplate: 'Total',
          Display: 'ROU Asset Balance - Added',
          PeriodQuarter: 'PeriodQuarter',
          data: 'AssetBalanceAddedReporting',
        },
        {
          LeaseTemplate: 'Total',
          Display: 'ROU Asset Balance - Amortization',
          PeriodQuarter: 'PeriodQuarter',
          data: 'AssetBalanceAmortizationReporting',
        },
        {
          LeaseTemplate: 'Total',
          Display: 'ROU Asset Balance - Adjustment',
          PeriodQuarter: 'PeriodQuarter',
          data: 'AssetBalanceAdjustmentReporting',
        },
        {
          LeaseTemplate: 'Total',
          Display: 'ROU Asset Balance - Closing',
          PeriodQuarter: 'PeriodQuarter',
          data: 'AssetBalanceClosingReporting',
        },
        {
          LeaseTemplate: 'Total',
          Display: 'Short Term Liability Balance',
          PeriodQuarter: 'PeriodQuarter',
          data: 'ShortTermLiabilityClosingReporting',
        },
        {
          LeaseTemplate: 'Total',
          Display: 'Long Term Liability Balance',
          PeriodQuarter: 'PeriodQuarter',
          data: 'LongTermLiabilityClosingReporting',
        },
        {
          LeaseTemplate: 'Total',
          Display: 'Total Liability Balance',
          PeriodQuarter: 'PeriodQuarter',
          data: 'LiabilityBalanceClosingReporting',
        },
      ],
    },
    {
      index: 2,
      name: 'Lease Costs',
      id: 'IFRS16-Quarterly-Lease-Cost',
      width: 200,
      showRowGrandTotals: true,
      texts: {
        grandTotal: 'Total Lease Cost',
      },
      combineWithIndex: 3,
      sortingOrder: {
        'Finance Lease Cost': 0,
        '- Depreciation of right-of-use Assets': 1,
        '- Interest on Lease Liabilities': 2,
        'Reporting Exceptions Cost Short-Term Leases': 3,
        'Reporting Exceptions Cost Low-Value Leases': 4,
        'Other Reporting Exceptions': 5,
        'Variable Lease Cost': 6,
        'Variable Cost of Indexed Payments': 7,
        'Sublease Income': 8,
        'Total Lease Cost': 9,
      },
      sortedColumnFieldName: 'LeaseTemplate',
      columnSortingOrder: {
        Lease: 1,
        'JE Lease': 2,
        'Real Estate Lease': 3,
        'Equipment Lease': 4,
        'Office Equipment Lease': 5,
        Total: 10,
      },
      fieldTransform: [
        {
          LeaseTemplate: 'LeaseTemplate',
          Display: 'Finance Lease Cost',
          PeriodQuarter: 'PeriodQuarter',
          data: 'FinanceLeaseCostReporting',
        },
        {
          LeaseTemplate: 'LeaseTemplate',
          Display: '- Depreciation of right-of-use Assets',
          PeriodQuarter: 'PeriodQuarter',
          data: 'DepreciationOfROUAssets',
        },
        {
          LeaseTemplate: 'LeaseTemplate',
          Display: '- Interest on Lease Liabilities',
          PeriodQuarter: 'PeriodQuarter',
          data: 'LeaseLiabilityInterestReporting',
        },
        {
          LeaseTemplate: 'LeaseTemplate',
          Display: 'Reporting Exceptions Cost Short-Term Leases',
          PeriodQuarter: 'PeriodQuarter',
          data: 'ShortTermLeaseReportingExceptionCostReporting',
        },
        {
          LeaseTemplate: 'LeaseTemplate',
          Display: 'Reporting Exceptions Cost Low-Value Leases',
          PeriodQuarter: 'PeriodQuarter',
          data: 'LowValueLeaseReportingExceptionCostReporting',
        },
        {
          LeaseTemplate: 'LeaseTemplate',
          Display: 'Other Reporting Exceptions',
          PeriodQuarter: 'PeriodQuarter',
          data: 'OtherReportingExceptionCostReporting',
        },
        {
          LeaseTemplate: 'LeaseTemplate',
          Display: 'Variable Lease Cost',
          PeriodQuarter: 'PeriodQuarter',
          data: 'VariableLeaseCostReporting',
        },
        {
          LeaseTemplate: 'LeaseTemplate',
          Display: 'Variable Cost of Indexed Payments',
          PeriodQuarter: 'PeriodQuarter',
          data: 'VariableLeaseCostOfIndexedPaymentsReporting',
        },
        {
          LeaseTemplate: 'LeaseTemplate',
          Display: 'Sublease Income',
          PeriodQuarter: 'PeriodQuarter',
          data: 'SubleaseIncome',
        },
        {
          LeaseTemplate: 'Total',
          Display: 'Finance Lease Cost',
          PeriodQuarter: 'PeriodQuarter',
          data: 'FinanceLeaseCostReporting',
        },
        {
          LeaseTemplate: 'Total',
          Display: '- Depreciation of right-of-use Assets',
          PeriodQuarter: 'PeriodQuarter',
          data: 'DepreciationOfROUAssets',
        },
        {
          LeaseTemplate: 'Total',
          Display: '- Interest on Lease Liabilities',
          PeriodQuarter: 'PeriodQuarter',
          data: 'LeaseLiabilityInterestReporting',
        },
        {
          LeaseTemplate: 'Total',
          Display: 'Reporting Exceptions Cost Short-Term Leases',
          PeriodQuarter: 'PeriodQuarter',
          data: 'ShortTermLeaseReportingExceptionCostReporting',
        },
        {
          LeaseTemplate: 'Total',
          Display: 'Reporting Exceptions Cost Low-Value Leases',
          PeriodQuarter: 'PeriodQuarter',
          data: 'LowValueLeaseReportingExceptionCostReporting',
        },
        {
          LeaseTemplate: 'Total',
          Display: 'Other Reporting Exceptions',
          PeriodQuarter: 'PeriodQuarter',
          data: 'OtherReportingExceptionCostReporting',
        },
        {
          LeaseTemplate: 'Total',
          Display: 'Variable Lease Cost',
          PeriodQuarter: 'PeriodQuarter',
          data: 'VariableLeaseCostReporting',
        },
        {
          LeaseTemplate: 'Total',
          Display: 'Variable Cost of Indexed Payments',
          PeriodQuarter: 'PeriodQuarter',
          data: 'VariableLeaseCostOfIndexedPaymentsReporting',
        },
        {
          LeaseTemplate: 'Total',
          Display: 'Sublease Income',
          PeriodQuarter: 'PeriodQuarter',
          data: 'SubleaseIncome',
        },
      ],
    },
    {
      index: 3,
      name: 'Reporting Exceptions Cost',
      id: 'IFRS16-Quarterly-Reporting-Exceptions-Cost',
      width: 200,
      sortingOrder: {
        'Asset Amortization': 0,
        'Finance Lease Cost': 0,
        'Lease Liability Interest': 0,
        'Operating Lease Cost': 0,
        'Short Term Lease and Exception Cost': 0,
        'Sublease Income': 0,
        'Variable Lease Cost Of Indexed Payments': 0,
        'Variable Lease Cost': 0,
      },
      sortedColumnFieldName: 'LeaseTemplate',
      columnSortingOrder: {
        Lease: 1,
        'JE Lease': 2,
        'Real Estate Lease': 3,
        'Equipment Lease': 4,
        'Office Equipment Lease': 5,
        Total: 10,
      },
      fieldTransform: [
        {
          LeaseTemplate: 'LeaseTemplate',
          Display: 'Sublease Income',
          PeriodQuarter: 'PeriodQuarter',
          data: 'SubleaseIncome',
        },
        {
          LeaseTemplate: 'LeaseTemplate',
          Display: 'Variable Lease Cost Of Indexed Payments',
          PeriodQuarter: 'PeriodQuarter',
          data: 'VariableLeaseCostOfIndexedPaymentsReporting',
        },
        {
          LeaseTemplate: 'LeaseTemplate',
          Display: 'Finance Lease Cost',
          PeriodQuarter: 'PeriodQuarter',
          data: 'VariableLeaseCostReporting',
        },
        {
          LeaseTemplate: 'Total',
          Display: 'Sublease Income',
          PeriodQuarter: 'PeriodQuarter',
          data: 'SubleaseIncome',
        },
        {
          LeaseTemplate: 'Total',
          Display: 'Variable Lease Cost Of Indexed Payments',
          PeriodQuarter: 'PeriodQuarter',
          data: 'VariableLeaseCostOfIndexedPaymentsReporting',
        },
        {
          LeaseTemplate: 'Total',
          Display: 'Finance Lease Cost',
          PeriodQuarter: 'PeriodQuarter',
          data: 'VariableLeaseCostReporting',
        },
      ],
    },
    {
      index: 4,
      name: 'Other Information',
      id: 'IFRS16-Quarterly-Other-Information',
      width: 200,
      sortingOrder: {
        'Cash Flows - Total': 0,
        'Cash Flows - Interest': 1,
        'Cash Flows - Principal Repayment': 2,
        'Right-of-use Assets Obtained In Exchange For New Finance Liabilities': 3,
        'Weighted-Average Remaining Years to Accounting Term': 4,
        'Weighted-Average Remaining Years to Expiration': 5,
        'Weighted-Average Incremental Borrowing Rate': 6,
      },
      sortedColumnFieldName: 'LeaseTemplate',
      columnSortingOrder: {
        'Real Estate Lease': 1,
        'Equipment Lease': 2,
        'Office Equipment Lease': 3,
        Total: 4,
      },
      fieldTransform: [
        {
          LeaseTemplate: 'LeaseTemplate',
          Display: 'Cash Flows - Total',
          PeriodQuarter: 'PeriodQuarter',
          data: 'CashFlowsTotalReporting',
        },
        {
          LeaseTemplate: 'LeaseTemplate',
          Display: 'Cash Flows - Interest',
          PeriodQuarter: 'PeriodQuarter',
          data: 'CashFlowsInterestReporting',
        },
        {
          LeaseTemplate: 'LeaseTemplate',
          Display: 'Cash Flows - Principal Repayment',
          PeriodQuarter: 'PeriodQuarter',
          data: 'CashFlowsPrincipalRepaymentReporting',
        },
        {
          LeaseTemplate: 'LeaseTemplate',
          Display:
            'Right-of-use Assets Obtained In Exchange For New Finance Liabilities',
          PeriodQuarter: 'PeriodQuarter',
          data: 'ROUAssetsObtainedInExchangeForNewFinanceLiabilities',
        },
        {
          LeaseTemplate: 'LeaseTemplate',
          Display: 'Weighted-Average Remaining Years to Accounting Term',
          PeriodQuarter: 'PeriodQuarter',
          data: 'WeightedAverageYearsRemainingToAccountingTermFinance',
        },
        {
          LeaseTemplate: 'LeaseTemplate',
          Display: 'Weighted-Average Remaining Years to Expiration',
          PeriodQuarter: 'PeriodQuarter',
          data: 'WeightedAverageYearsRemainingToExpirationFinance',
        },
        {
          LeaseTemplate: 'LeaseTemplate',
          Display: 'Weighted-Average Incremental Borrowing Rate',
          PeriodQuarter: 'PeriodQuarter',
          data: 'WeightedAverageIncrementalBorrowingRate',
        },
        // Totals
        {
          LeaseTemplate: 'Total',
          Display: 'Cash Flows - Total',
          PeriodQuarter: 'PeriodQuarter',
          data: 'CashFlowsTotalReporting',
        },
        {
          LeaseTemplate: 'Total',
          Display: 'Cash Flows - Interest',
          PeriodQuarter: 'PeriodQuarter',
          data: 'CashFlowsInterestReporting',
        },
        {
          LeaseTemplate: 'Total',
          Display: 'Cash Flows - Principal Repayment',
          PeriodQuarter: 'PeriodQuarter',
          data: 'CashFlowsPrincipalRepaymentReporting',
        },
        {
          LeaseTemplate: 'Total',
          Display:
            'Right-of-use Assets Obtained In Exchange For New Finance Liabilities',
          PeriodQuarter: 'PeriodQuarter',
          data: 'ROUAssetsObtainedInExchangeForNewFinanceLiabilities',
        },
        {
          LeaseTemplate: 'Total',
          Display: 'Weighted-Average Remaining Years to Accounting Term',
          PeriodQuarter: 'PeriodQuarter',
          data: 'WeightedAverageYearsRemainingToAccountingTermFinance',
        },
        {
          LeaseTemplate: 'Total',
          Display: 'Weighted-Average Remaining Years to Expiration',
          PeriodQuarter: 'PeriodQuarter',
          data: 'WeightedAverageYearsRemainingToExpirationFinance',
        },
        {
          LeaseTemplate: 'Total',
          Display: 'Weighted-Average Incremental Borrowing Rate',
          PeriodQuarter: 'PeriodQuarter',
          data: 'WeightedAverageIncrementalBorrowingRate',
        },
      ],
    },
    {
      index: 5,
      name: 'Liability Maturity',
      id: 'IFRS16-Quarterly-Liability-Maturity',
      filterData: [
        { displayKey: '5 years', valueKey: 6 },
        { displayKey: '10 years', valueKey: 11 },
      ],
      filterBy: 'PeriodYear',
      filterInitialValue: { displayKey: '5 years', valueKey: 6 },
      width: 200,
      sortingOrder: {
        Thereafter: 100,
      },
      sortedColumnFieldName: 'LeaseTemplate',
      columnSortingOrder: {
        'Real Estate Lease': 1,
        'Equipment Lease': 2,
        'Office Equipment Lease': 3,
        Total: 4,
      },
      fieldTransform: [
        {
          LeaseTemplate: 'LeaseTemplate',
          PeriodYear: 'PeriodYear',
          data: 'ScheduledPaymentsReporting',
          modify: {
            replace: 'ScheduledPaymentsReporting',
            newData: 'RemainingPaymentsReporting',
            compareWith: 'PeriodYear',
            compareWithX: 'LeaseTemplate',
            offset: -1,
            indexes: 'last',
            caption: 'Thereafter',
          },
        },
        {
          LeaseTemplate: 'Total',
          PeriodYear: 'PeriodYear',
          data: 'ScheduledPaymentsReporting',
          modify: {
            replace: 'ScheduledPaymentsReporting',
            newData: 'RemainingPaymentsReporting',
            compareWith: 'PeriodYear',
            compareWithX: 'LeaseTemplate',
            offset: -1,
            indexes: 'last',
            caption: 'Thereafter',
          },
        },
      ],
    },
    {
      index: 6,
      name: 'Reconciliation of Lease Liabilities',
      id: 'IFRS16-Quarterly-Reconciliation-of-Lease-Liabilities',
      width: 200,
      sortingOrder: {
        'Weighted-average Remaining Years to Accounting Term': 0,
        'Weighted-average Remaining Years to Expiration': 1,
        'Weighted-average Incremental Borrowing Rate': 2,
        'Total Undiscounted Lease Liability': 3,
        'Imputed Interest': 4,
        'Total Discounted Lease Liability': 5,
      },
      columnSortingOrder: {
        'Equipment Lease': 0,
        'Real Estate Lease': 1,
        Total: 100,
      },
      texts: {
        grandTotal: 'Total',
      },
      showColumnGrandTotals: true,
      fieldTransform: [
        {
          LeaseTemplate: 'LeaseTemplate',
          Display: 'Weighted-average Remaining Years to Accounting Term',
          data: 'WeightedAverageYearsRemainingToAccountingTerm',
        },
        {
          LeaseTemplate: 'LeaseTemplate',
          Display: 'Weighted-average Remaining Years to Expiration',
          data: 'WeightedAverageYearsRemainingToExpiration',
        },
        {
          LeaseTemplate: 'LeaseTemplate',
          Display: 'Weighted-average Incremental Borrowing Rate',
          data: 'WeightedAverageDiscountRate',
        },
        {
          LeaseTemplate: 'LeaseTemplate',
          Display: 'Total Undiscounted Lease Liability',
          data: 'TotalUndiscountedLeaseLiability',
        },
        {
          LeaseTemplate: 'LeaseTemplate',
          Display: 'Imputed Interest',
          data: 'ImputedInterest',
        },
        {
          LeaseTemplate: 'LeaseTemplate',
          Display: 'Total Discounted Lease Liability',
          data: 'TotalUndiscountedLeaseLiability',
        },
      ],
    },
    {
      index: 7,
      name: 'Future Commitments',
      id: 'IFRS16-Quarterly-Future-Commitments',
      width: 200,
      sortingOrder: {},
      filterData: [
        { displayKey: '5 years', valueKey: 6 },
        { displayKey: '10 years', valueKey: 11 },
      ],
      filterBy: 'PeriodYear',
      filterInitialValue: { displayKey: '5 years', valueKey: 6 },
      fieldTransform: [
        {
          LeaseTemplate: 'LeaseTemplate',
          PeriodYear: 'PeriodYear',
          data: 'ScheduledPaymentsReporting',
          modify: {
            replace: 'ScheduledPaymentsReporting',
            newData: 'RemainingPaymentsReporting',
            compareWith: 'PeriodYear',
            offset: -1,
            indexes: 'last',
            caption: 'Thereafter',
          },
        },
        {
          LeaseTemplate: 'Total',
          PeriodYear: 'PeriodYear',
          data: 'ScheduledPaymentsReporting',
          modify: {
            replace: 'ScheduledPaymentsReporting',
            newData: 'RemainingPaymentsReporting',
            compareWith: 'PeriodYear',
            offset: -1,
            indexes: 'last',
            caption: 'Thereafter',
          },
        },
      ],
    },
  ],
};
