# To be used by Mango-SPA Only if not using IIS or .NET web server to serve the app

worker_processes auto;

error_log /var/log/nginx/error.log notice;
pid /var/run/nginx.pid;

events {
  worker_connections 1024;
}

http {
  include /etc/nginx/mime.types;
  default_type application/octet-stream;

  log_format main '$remote_addr - $remote_user [$time_local] "$request" '
  '$status $body_bytes_sent "$http_referer" '
  '"$http_user_agent" "$http_x_forwarded_for"';

  access_log /var/log/nginx/access.log main;

  sendfile on;

  keepalive_timeout 65;

  # Enable Gzip compression
  gzip on;

  gzip_vary on;
  gzip_buffers 128 4k;

  # Compression level (1-9)
  gzip_comp_level 9;

  # Don't compress anything under 256 bytes
  gzip_min_length 256;

  # Compress output of these MIME-types
  gzip_types
  application/atom+xml
  application/javascript
  application/json
  application/rss+xml
  application/vnd.ms-fontobject
  application/x-font-ttf
  application/x-font-opentype
  application/x-font-truetype
  application/x-javascript
  application/x-web-app-manifest+json
  application/xhtml+xml
  application/xml
  font/eot
  font/opentype
  font/otf
  image/svg+xml
  image/x-icon
  image/vnd.microsoft.icon
  text/css
  text/plain
  text/javascript
  text/x-component;

  # Disable gzip for bad browsers
  gzip_disable "MSIE [1-6]\.(?!.*SV1)";

  server {
    listen 8000;
    listen [::]:8000;
    server_name localhost;

    location / {
      root /usr/share/nginx/html;
      index index.html index.htm;
      try_files $uri $uri/ /index.html;
    }

    # Headers to prevent Cross-site scripting (XSS) attacks
    add_header X-Frame-Options SAMEORIGIN;
    add_header X-Content-Type-Options nosniff;
    add_header X-XSS-Protection "1; mode=block";

    # Should only be turned on in upper environments
    # add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;

    sub_filter_once off;
    sub_filter random-csp-nonce $request_id;

    # Temporary - using 'unsafe-inline'
    #add_header Content-Security-Policy "default-src 'self';
    #              connect-src 'self' *.crem.aws.dshrp.com/ *.corp.virtualpremise.com:*/;
		#							frame-src 'self';
		#							script-src 'self' *.costar.com *.glancecdn.net *.google-analytics.com;
    #              font-src 'self' *.googleapis.com *.gstatic.com;
		#							style-src 'self' 'unsafe-inline';
		#							frame-ancestors 'self';
		#							img-src 'self' data: *.corp.virtualpremise.com:*/;
		#							manifest-src 'self';
		#							media-src 'self';
		#							object-src 'self';
		#							worker-src 'self';" always;

    # Official one to use
    # add_header Content-Security-Policy "default-src 'self';
    #     connect-src 'self' *.crem.aws.dshrp.com/ *.corp.virtualpremise.com:*/;
    #     font-src 'self' *.googleapis.com *.gstatic.com;
    #     frame-src 'self';
    #     script-src 'self' *.costar.com *.glancecdn.net *.google-analytics.com;
    #     style-src 'self' 'nonce-$request_id' *.googleapis.com;
    #     frame-ancestors 'self';
    #     img-src 'self' data: *.corp.virtualpremise.com:*/;
    #     manifest-src 'self';
    #     media-src 'self';
    #     object-src 'self';
    #     worker-src 'self';" always;
  }
}

