import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { Service, Strategy, ListPageQuery } from '../../../../../app.service';

@Component({
  selector: 'overview',
  templateUrl: './overview.component.html',
  styleUrls: ['./overview.component.scss']
})
export class StrategyOverviewComponent implements OnInit {

	strategies : Strategy[];
	columns : Array<any>;
	queries : ListPageQuery[];
	rowClickRoute : String;
	addWizards : Array<any>;
	keyFields : String[];

	constructor( private service : Service, private router: Router, private route: ActivatedRoute ) { }

	ngOnInit() {
		this.strategies = this.service.getStrategies();
		this.queries = this.service.getListPageQueriesByObjectType('strategy');

		this.rowClickRoute = '../../portfolio/property/%%_strategyId_%%/mystrategythree';
		this.keyFields = ["strategyId"];

		this.addWizards = [
			{	name : "Strategy" },
		];
		this.columns = [
      {
        dataField: "buildingName",
        alignment: "left",
        visible: true,
        dataType: "string",
        fixed: true,
        caption: "Building Name",
      },
      {
        dataField: "strategyId",
        alignment: "left",
        visible: false,
        dataType: "number",
      },
      {
        dataField: "address",
        alignment: "left",
        visible: true,
        dataType: "string",
      },
      {
        dataField: "city",
        alignment: "left",
        visible: true,
        dataType: "string",
      },
      {
        dataField: "state",
        alignment: "left",
        visible: true,
        dataType: "string",
      },
      {
        dataField: "country",
        alignment: "left",
        visible: true,
        dataType: "string",
      },
      {
        dataField: "currentStrategy",
        alignment: "left",
        visible: true,
        dataType: "string",
        width: "160px",
      },
      {
        dataField: "strategyComments",
        alignment: "left",
        visible: true,
        dataType: "string",
        width: "200px",
      },
      {
        dataField: "currentRentCurrency",
        alignment: "right",
        visible: true,
        dataType: "number",
        format: { style: "currency", currency: "USD", useGrouping: true },
        caption: "Current Rent (USD)",
        width: "200px",
      },
      {
        dataField: "currentRentSF",
        alignment: "right",
        visible: true,
        dataType: "number",
        format: { style: "currency", currency: "USD", useGrouping: true },
        caption: "Current Rent/SF",
        width: "160px",
      },
      {
        dataField: "currentVsMarketRentSF",
        alignment: "right",
        visible: true,
        dataType: "number",
        format: { style: "currency", currency: "USD", useGrouping: true },
        caption: "Current vs Market Rent/SF",
        width: "260px",
      },
      {
        dataField: "currentVsMarketRent",
        alignment: "right",
        visible: true,
        dataType: "number",
        format: { type: "percent", precision: 0, },
        caption: "Current Rent/SF",
        width: "160px",
      },
      {
        dataField: "remainingLeaseObligation",
        alignment: "right",
        visible: true,
        dataType: "number",
        format: { style: "currency", currency: "USD", useGrouping: true },
        caption: "Remaining Lease Obligation (USD)",
        width: "290px",
      },
      {
        dataField: "currentExpiration",
        alignment: "right",
        visible: true,
        dataType: "string",
        width: "200px",
      },
      {
        dataField: "rentableSF",
        alignment: "right",
        visible: true,
        precision: 2,
        dataType: "number",
        width: "150px",
      },
      {
        dataField: "leaseFlexibilityScore",
        alignment: "right",
        visible: true,
        precision: 0,
        dataType: "number",
        width: "200px",
      },
      {
        dataField: "activeLeaseOptions",
        alignment: "right",
        visible: true,
        dataType: "number",
        precision: 0,
        caption: "# Active Lease Options",
        width: "240px",
      },
      {
        dataField: "currentHeadCount",
        alignment: "right",
        visible: true,
        precision: 0,
        dataType: "number",
        width: "200px",
      },
      {
        dataField: "currentCapacity",
        alignment: "right",
        visible: true,
        precision: 0,
        dataType: "number",
        width: "200px",
      },
      {
        dataField: "currentSeatsAvailable",
        alignment: "right",
        visible: true,
        precision: 0,
        dataType: "number",
        width: "240px",
      },
      {
        dataField: "currentUtilization",
        alignment: "right",
        visible: true,
        dataType: "number",
        precision: 2,
        width: "200px",
      },
      {
        dataField: "strategyYear",
        alignment: "right",
        visible: true,
        dataType: "year",
        width: "200px",
      },
      {
        dataField: "budgetedCapital",
        alignment: "right",
        visible: true,
        dataType: "number",
        format: { style: "currency", currency: "USD", useGrouping: true },
        width: "200px",
      },
      {
        dataField: "systemLeaseId",
        alignment: "right",
        visible: true,
        dataType: "number",
        caption: "System Lease ID",
        width: "200px",
      },
      {
        dataField: "marketRentProperty",
        alignment: "right",
        visible: true,
        dataType: "number",
        format: { style: "currency", currency: "USD", useGrouping: true },
        caption: "Market Rent - Property",
        width: "240px",
      },
      {
        dataField: "marketRentSubMarket",
        alignment: "right",
        visible: true,
        dataType: "number",
        format: { style: "currency", currency: "USD", useGrouping: true },
        caption: "Market Rent - Submarket",
        width: "240px",
      },
      {
        dataField: "vacantSFProperty",
        alignment: "right",
        visible: true,
        dataType: "number",
        precision: 2,
        caption: "Vacant SF - Property",
        width: "240px",
      },
      {
        dataField: "vacantSFSubMarketRating",
        alignment: "right",
        visible: true,
        dataType: "number",
        precision: 2,
        caption: "Vacant SF - Submarket Rating",
        width: "280px",
      },
      {
        dataField: "vacantSFSubMarket",
        alignment: "right",
        visible: true,
        dataType: "number",
        precision: 2,
        caption: "Vacant SF - Submarket",
        width: "240px",
      },
      {
        dataField: "vacancyRateProperty",
        alignment: "right",
        visible: true,
        dataType: "number",
        format: { type: "percent", precision: 2, },
        caption: "Vacancy Rate - Property",
        width: "240px",
      },
      {
        dataField: "vacancyRateSubMarketRating",
        alignment: "right",
        visible: true,
        dataType: "number",
        format: { type: "percent", precision: 2, },
        caption: "Vacancy Rate - Submarket Rating",
        width: "280px",
      },
      {
        dataField: "vacancyRateSubMarket",
        alignment: "right",
        visible: true,
        dataType: "number",
        format: { type: "percent", precision: 2, },
        caption: "Vacancy Rate - Submarket",
        width: "240px",
      },
      {
        dataField: "availableSFProperty",
        alignment: "right",
        visible: true,
        dataType: "number",
        precision: 2,
        caption: "Available SF - Property",
        width: "280px",
      },
      {
        dataField: "availableSFSubMarketPeerGroup",
        alignment: "right",
        visible: true,
        dataType: "number",
        precision: 2,
        caption: "Available SF - Submarket Peer Group",
        width: "300px",
      },
      {
        dataField: "availableSFSubMarket",
        alignment: "right",
        visible: true,
        dataType: "number",
        precision: 2,
        caption: "Available SF - Submarket",
        width: "240px",
      },
      {
        dataField: "availabilityRateProperty",
        alignment: "right",
        visible: true,
        dataType: "number",
        format: { type: "percent", precision: 2, },
        caption: "Availability Rate - Property",
        width: "240px",
      },
      {
        dataField: "availabilityRateSubMarketRating",
        alignment: "right",
        visible: true,
        dataType: "number",
        format: { type: "percent", precision: 2, },
        caption: "Availability Rate - Submarket Rating",
        width: "300px",
      },
      {
        dataField: "availabilityRateSubMarket",
        alignment: "right",
        visible: true,
        dataType: "number",
        format: { type: "percent", precision: 2, },
        caption: "Availability Rate - Submarket",
        width: "300px",
      },
      {
        dataField: "subletSFProperty",
        alignment: "right",
        visible: true,
        dataType: "number",
        precision: 2,
        caption: "Sublet SF - Property",
        width: "240px",
      },
      {
        dataField: "subletSFSubMarketRating",
        alignment: "right",
        visible: true,
        dataType: "number",
        precision: 2,
        caption: "Sublet SF - Submarket Rating",
        width: "280px",
      },
      {
        dataField: "subletSFSubMarket",
        alignment: "right",
        visible: true,
        dataType: "number",
        precision: 2,
        caption: "Sublet SF - Submarket",
        width: "280px",
      },
      {
        dataField: "twelveMoNetAbsorptionSFProperty",
        alignment: "right",
        visible: true,
        dataType: "number",
        precision: 2,
        caption: "12 Mo Net Absorption SF - Property",
        width: "320px",
      },
      {
        dataField: "twelveMoNetAbsorptionSFSubMarketRating",
        alignment: "right",
        visible: true,
        dataType: "number",
        precision: 2,
        caption: "12 Mo Net Absorption SF - Submarket Rating",
        width: "360px",
      },
      {
        dataField: "twelveMoNetAbsorptionSFSubMarket",
        alignment: "right",
        visible: true,
        dataType: "number",
        precision: 2,
        caption: "12 Mo Net Absorption SF - Submarket",
        width: "320px",
      },
      {
        dataField: "sixMoLeasingProbabilitySubMarketRating",
        alignment: "right",
        visible: true,
        dataType: "number",
        format: { type: "percent", precision: 2, },
        caption: "6 Mo Leasing Probability - Submarket Rating",
        width: "360px",
      },
      {
        dataField: "sixMoLeasingProbabilitySubMarket",
        alignment: "right",
        visible: true,
        dataType: "number",
        format: { type: "percent", precision: 2, },
        caption: "6 Mo Leasing Probability - Submarket",
        width: "300px",
      },
      {
        dataField: "lastUpdated",
        alignment: "right",
        visible: true,
        dataType: "string",
        width: "180px",
      },
      {
        dataField: "lastUpdatedBy",
        alignment: "right",
        visible: true,
        dataType: "number",
        width: "180px",
      },
		];
	}

}