export interface AccountingEvent {
  leaseRecognitionScheduleID: number | null;
  leaseRecognitionID: number;
  masterScheduleID: number;
  measureEvent: string;
  remeasureTypeID: number;
  copiedFromScheduleID: number;
  isActive: boolean;
  isPublished: boolean;
  totalAmount: number;
  classificationID: number;
  journalEntryProfileID: number;
  beginDate: string;
  endDate: string;
  fromDateOptionID: number;
  toDateOptionID: number;
  fromDateFormItemID: number | null;
  toDateFormItemID: number | null;
  includeFromFirst: boolean;
  firstMonthOverwriteDate: string | null;
  termInDays: number;
  termInPeriods: number;
  termInMonths: number;
  termInYears: number;
  termString: string;
  isReportingException: boolean;
  exceptionReason: string | null;
  exceptionOtherReason: string;
  isImpaired: boolean;
  comments: string;
  test1: boolean;
  test2: boolean;
  test3: number;
  test4: number;
  test5: boolean;
  classificationTestResult: string | null;
  classificationTestResultReason: string | null;
  isClassificationTestResultMatched: boolean | null;
  economicLifeYears: number | null;
  fmv: number | null;
  implicitRate: number | null;
  residualValues: ResidualValues;
  amortizationMethodTypeID: number;
  amortizationProfileID: number;
  manualProfileName: string | null;
  isIncome: boolean;
  overrideProfile: boolean;
  discountRateProfileID: number;
  discountRate: number;
  discountRateTypeID: number;
  annualRateTypeID: number;
  effectiveRate: number;
  modificationImpactsScope: boolean;
  localCurrencyID: number;
  localCurrency: string;
  localCurrencyDecimalPrecision: number;
  functionalCurrencyID: number;
  functionalCurrency: string;
  functionalCurrencyDecimalPrecision: number;
  functionalCurrencyRate: number;
  rouAssetMethodID: number | null;
  rouAssetObtainedDate: string | null;
  rouAssetObtainedAmount: number | null;
  functionalROUAssetObtainedAmount: number | null;
  openingAssetBalance: number;
  functionalOpeningAssetBalance: number;
  openingBalance: number;
  overrideOpeningBalance: boolean;
  previousAssetBalance: number;
  systemAssetAdjustment: number;
  manualAssetAdjustment: number;
  adjustmentAmount: number;
  levelExpense: number;
  functionalLevelExpense: number;
  directCosts: number;
  functionalDirectCosts: number;
  presentValue: number;
  compoundFrequencyType: number;
  paymentInArrears: boolean;
  openingLiabilityBalance: number;
  previousLiabilityBalance: number;
  liabilityAdjustmentAmount: number;
  adjustmentGainLoss: number;
  functionalAdjustmentGainLoss: number;
  terminationFee: number;
  functionalTerminationFee: number | null;
  // assetAdjustmentAmount: number;
  // straightLineExpense: number;
  // straightLineExpenseDaily: number;
  assetAmortization: number;
  functionalAssetAmortization: number;
}

export interface ProperPreviousAmortizationPeriod {
  periodDays: number[];
  calendarPeriodStartDate: string;
  calendarPeriodEndDate: string;
  optionAmount: number;
  otherAmount: number;
  periodLocalCash: number;
  leaseRecognitionPeriodId: number;
  leaseRecognitionAmortizationID: number;
  year: number;
  month: number;
  displayPeriod: string;
  cashApAmount: number;
  adjustmentAmount: number | null;
  amortizationScheduleKey: number | null;
  deferredLeaseExpense: number | null;
  deferredLeaseExpenseBalance: number | null;
  straightLineExpense: number | null;
  capitalLeaseAssetAmount: number | null;
  capitalLeaseLiabilityAmount: number | null;
  depreciationExpense: number | null;
  liabilityAdjustmentAmount: number | null;
  liabilityReductionAmount: number;
  discountRate: number | null;
  npv: number | null;
  interestExpense: number;
  isBeginningBalance: boolean;
  isJournalEntryApproved: boolean;
  isManualAdjustment: boolean;
  presentValueRecalc: number | null;
  jeStatus: string;
  createdBy: number;
  createdDate: string;
  approvedBy: number;
  approvedDate: string;
  exportedDate: string;
  exportedBy: number;
  exportSystemBatchNumber: number;
  exportClientBatchNumber: number | null;
  rouAsset: number;
  assetAmortization: number;
  typeALiabilityAmount: number | null;
  typeBLiabilityAmount: number;
  levelExpense: number;
  createdByScheduleId: number;
  shortTermLiability: number;
  longTermLiability: number;
  remainingTermInMonths: number;
  periodIndex: number;
  remainingPayments: number;
  originalCash: number | null;
  accumulatedAssetAmortization: number;
  shortTermLiabilityReductionAmount: number;
  longTermLiabilityReductionAmount: number;
  functional_AssetBalance: number;
  functional_AccumulatedAssetAmortization: number;
  functional_AssetAmortization: number;
  functional_AssetAdjustmentAmount: number | null;
  functional_LevelExpense: number;
  functional_RouassetInterestExpense: number;
  functionalRate: number;
  cumulativeStraightLineExpense: number | null;
  cumulativeCash: number;
  cumulativeAdjustments: number;
  cumulativeInterestExpense: number;
  cumulativeDepreciationExpense: number | null;
  cumulativeDeferredLeaseExpense: number | null;
  cumulativeAdjustmentAmount: number;
  cumulativeLiabilityAdjustmentAmount: number;
  cumulativeLiabilityReductionAmount: number;
  cumulativeAssetAmortization: number | null;
  cumulativeLevelExpense: number;
  assetBalanceOpening: number | null;
  periodStart: string;
  periodEnd: string;
  actualDaysInPeriod: number;
  isRetro: boolean;
  retroScheduleId: number;
  period: number;
  rouAssetBeginBalance: number;
  functionalAssetBeginBalance: number;
  liabilityBeginBalance: number;
  shortTermLiabilityBeginBalance: number;
  longTermLiabilityBeginBalance: number;
  shortTermLiabilityAdjustment: number | null;
  longTermLiabilityAdjustment: number | null;
  parentScheduleId: number;
  daysInFullPeriod: number;
  daysInFullYear: number;
  quarter: number;
  calendarPeriod: number;
  currentPortionOfInvestment: number | null;
  currentPortionUnearnedIncome: number | null;
  unearnedIncome: number | null;
  liabilityClosingBalance: number;
  periodEvent: string;
  isLastPeriod: boolean;
  scheduleIndex: number;
  isLiabilityMatured: boolean;
}

export interface CalculationSupports {
  leaseAbstractId: number;
  leaseRecognitionScheduleId: number | null;
  copiedFromScheduleId: number;
  properPreviousScheduleId: number;
  properPreviousAmortizationPeriod: ProperPreviousAmortizationPeriod;
  controlStatements: ControlStatements;
  scheduleCurrency: Currency;
  functionalCurrency: Currency;
  selectedPayments: SelectedPayment[];
}

export interface ControlStatements {
  remeasureTypeID: number;
  isDay1Remeasure: boolean;
  isDayXRemeasure: boolean;
  isGappedRemeasure: boolean;
  isMidPeriodGappedRemeasure: boolean;
  isMidPeriodRemeasure: boolean;
  isRetroAdjustment: boolean;
  originalFromDate: string;
  previousEffectiveRate: number;
  previousFunctionalCurrencyRate: number;
  calendarStartDate: string;
  calendarEndDate: string;
  paymentDueOnDayOne: number;
  firstHalfCash: number | null;
  frequency: number;
}

export interface Currency {
  exchangeRateID: number;
  targetCurrency: string;
  decimalPrecision: number;
}

export interface SelectedPayment {
  glEventID: number;
  paymentEventSource: string;
}

export interface ResidualValues {
  estimatedResidualValue: number;
  guaranteedResidualValue: number;
  guaranteedAmtReflectedInPayments: number;
  rvGuaranteedBy3rdParty: number;
  doesLessorExplicitylyExemptLessee: boolean;
  rvGuaranteedByLessee: number;
  amountProbableOfBeingOwedByLessee: number;
  unguaranteedResidualValue: number;
  amtNotReflectedInPVofPayments: number;
  pVofAmtNotReflectedInPayments: number;
}

export interface AccountingEventPayload {
  accountingEvent: AccountingEvent;
  calculationSupports: CalculationSupports;
}
