export class FinancialModel {
  implicitRate: number;
  openingLiabilityBalance: number;
  functional_TerminationFee: number;
  functional_DirectCostsTotal: number;
  totalPayments: number;
  systemAssetAdjustment: number;
  adjustment: number;
  adjustmentGainLoss: number;
  functional_AdjustmentGainLoss: number;
  functional_OpeningAssetBalance: number;
  levelExpense: number;
  functional_LevelExpense: number;
  functional_AssetAmortization: number;
  rouAssetObtainedAmount: number;
  functionalROUAssetObtainedAmount: number;
  classificationID: number;
  pageMode: string;
  measureEvent: string;
  localCurrency: string;
  localCurrencyDecimalPrecision: number;
  undiscountedAmount: number;
  terminationFee: number;
  assetBalance: number;
  previousBalance: number;
  directCost: number;
  manualAssetAdjustment: number;
  totalAdjustment: number;
  termInDays: number;
  termInMonths: number;
  termInPeriods: number;
  termInYears: number;
  termString: string;
  carryForward: number;
  numberOfDays: number;
  presentValue: number;
  effectiveRate: number;
  previousLiabilityBalance: number;
  liabilityAdjustmentAmount: number;
  straightLineExpense: number;
  straightLineExpenseDaily: number;
  optionCharges: number;
  amortizationMethodTypeID: number;
  assetAmortization: number;
  openingAssetBalance: number;
  previousAssetBalance: number;
  openingBalance: number;
  overrideOpeningBalance: boolean;

  constructor() {
    this.effectiveRate = 0;
    this.presentValue = 0;
    this.implicitRate = 0;
    this.openingLiabilityBalance = 0;
    this.totalPayments = 0;
    this.terminationFee = 0;
    this.functional_TerminationFee = 0;
    this.directCost = 0;
    this.functional_DirectCostsTotal = 0;
    this.previousAssetBalance = 0;
    this.liabilityAdjustmentAmount = 0;
    this.systemAssetAdjustment = 0;
    this.adjustment = 0;
    this.adjustmentGainLoss = 0;
    this.functional_AdjustmentGainLoss = 0;
    this.openingAssetBalance = 0;
    this.functional_OpeningAssetBalance = 0;
    this.levelExpense = 0;
    this.functional_LevelExpense = 0;
    this.assetAmortization = 0;
    this.functional_AssetAmortization = 0;
    this.rouAssetObtainedAmount = 0;
    this.functionalROUAssetObtainedAmount = 0;
    this.functional_DirectCostsTotal = 0;
    this.classificationID = 0;
    this.pageMode = '';
    this.measureEvent = '';
    this.localCurrency = '';
    this.localCurrencyDecimalPrecision = 0;
    this.undiscountedAmount = 0;
    this.assetBalance = 0;
    this.previousBalance = 0;
    this.directCost = 0;
    this.manualAssetAdjustment = 0;
    this.totalAdjustment = 0;
    this.termInDays = 0;
    this.termInMonths = 0;
    this.termInPeriods = 0;
    this.termInYears = 0;
    this.termString = '';
    this.carryForward = 0;
    this.numberOfDays = 0;
    this.previousLiabilityBalance = 0;
    this.straightLineExpense = 0;
    this.straightLineExpenseDaily = 0;
    this.optionCharges = 0;
    this.assetAmortization = 0;
    this.previousAssetBalance = 0;
    this.openingBalance = 0;
    this.overrideOpeningBalance = false;
  }
}
