export interface DropdownValue {
  displayString: string;
  intValue: number;
  stringValue: any;
}

export interface DashboardCard {
  id: number;
  dashboardId: number;
  dashboardCardTypeId: number;
  cardJSONSchema: string;
}

export interface DashboardVm {
  calendarFilterData: DropdownValue[];
  clientSite: string;
  portfolioFilterData: DropdownValue[];
  yearFilterData: DropdownValue[];
  cardsMetaData: DashboardCard[];
  selectedPortfolioIds: string;
  selectedCalendarId: number;
  selectedYear: string;
}

export interface ReportingLeaseVm {
  LeaseAbstractID: number;
  LeaseSourceImportID: string;
  LeaseObjectTypeTypeID: number;
  LeaseTemplate: string;
  LeaseTemplateBillingType: string;
  LeaseTemplateBillingTypeID: number;
  Portfolio: string;
  PortfolioID: number;
  Calendar: string;
  CalendarID: number;
  BuildingID: number;
  BuildingSourceImportID: string;
  BuildingStatus: boolean;
  BuildingObjectTypeTypeID: number;
  BuildingTemplate: string;
  BuildingTemplateBillingType: string;
  BuildingTemplateBillingTypeID: number;
  PremiseID: number;
  SystemLeaseStatus: string;
  ClientLeaseID: string;
  OwnershipType: string;
  BuildingName: string;
  LeaseName: string;
  LeaseDisplayString: string;
  Address1: string;
  Address2: string;
  City: string;
  StateName: string;
  ZipCode: string;
  Country: string;
  BuildingTypeID: number;
  BuildingType: string;
  BuildingRentableArea: number;
  BuildingMeasureUnits: string;
  BuildingSF: number;
  BuildingSM: number;
  BuildingHierarchyID: number;
  LeaseHierarchyID: number;
  LeaseStatus: string;
  LeaseStatusID: number;
  CurrentCommencementDate: Date;
  CurrentExpirationDate: Date;
  RemainingLeaseTerminYears: number;
  LeaseRentableArea: number;
  LeaseMeasureUnits: string;
  LeaseSF: number;
  LeaseSM: number;
  Hierarchy: string;
  Hierarchy1ID: number;
  Hierarchy2ID: number;
  Hierarchy3ID: number;
  Hierarchy4ID: number;
  Hierarchy5ID: number;
  MeasureUnitsID: number;
  LeaseCurrencyID: number;
  LeaseCurrencyISO: string;
  TenantLegalName: string;
  AccountingType: string;
  LandLordName: string;
  LeaseTenantHierarchyID: number;
  BuildingArchivedByID: number;
  BuildingArchivedBy: string;
  buildingArchivedDate: Date;
  BuildingCreatedDate: Date;
  LeaseArchivedByID: number;
  LeaseArchivedBy: string;
  LeaseArchivedDate: Date;
  LeaseCreatedDate: Date;
  LeaseModifiedDate: Date;
  LeaseActive: boolean;
  leaselabel: string;
  AccountingWorkFlowStatusStep: number;
  AccountingWorkFlowStatusID: number;
  AccountingWorkFlowStatusDisplay: string;
  AccountingWorkFlowStatus: string;
  CachedDate: Date;
  LeaseAllocationDisplay1: string;
  LeaseAllocationDisplay2: string;
  LeaseAllocationDisplayString: string;
  LeaseAllocationDisplayString2: string;
}

export const ColumnOverrideArray = {
  Periods: {
    leaseAbstractID: 'p.leaseAbstractID',
    systemLeaseID: 'p.systemLeaseID',
    portfolio: 'p.portfolio',
    portfolioID: 'p.portfolioID',
    calendarID: 'p.calendarID',
    cashdate: 'p.cashdate',
  },
  Alerts: {
    leaseAbstractID: 'la.leaseAbstractID',
    alertRuleID: 'la.alertRuleID',
    alertTypeID: 't.alertTypeID',
    alertRuleSeverityID: 's.alertRuleSeverityID',
  },
};
export const ColumnArray = {
  Leases: {
    leaseAbstractID: 'number',
    leaseSourceImportID: 'string',
    leaseObjectTypeTypeID: 'number',
    leaseTemplate: 'string',
    leaseTemplateBillingType: 'string',
    leaseTemplateBillingTypeID: 'number',
    portfolio: 'string',
    portfolioID: 'number',
    calendar: 'string',
    calendarID: 'number',
    buildingID: 'number',
    buildingSourceImportID: 'string',
    buildingStatus: 'boolean',
    buildingObjectTypeTypeID: 'number',
    buildingTemplate: 'string',
    buildingTemplateBillingType: 'string',
    buildingTemplateBillingTypeID: 'number',
    premiseID: 'number',
    systemLeaseStatus: 'string',
    clientLeaseID: 'string',
    ownershipType: 'string',
    buildingName: 'string',
    leaseName: 'string',
    leaseDisplayString: 'string',
    address1: 'string',
    address2: 'string',
    city: 'string',
    stateName: 'string',
    zipCode: 'string',
    country: 'string',
    buildingTypeID: 'number',
    buildingType: 'string',
    buildingRentableArea: 'number',
    buildingMeasureUnits: 'string',
    buildingSF: 'number',
    buildingSM: 'number',
    buildingHierarchyID: 'number',
    leaseHierarchyID: 'number',
    leaseStatus: 'string',
    leaseStatusID: 'number',
    currentCommencementDate: 'Date',
    currentExpirationDate: 'Date',
    remainingLeaseTerminYears: 'number',
    leaseRentableArea: 'number',
    leaseMeasureUnits: 'string',
    leaseSF: 'number',
    leaseSM: 'number',
    hierarchy: 'string',
    hierarchy1ID: 'number',
    hierarchy2ID: 'number',
    hierarchy3ID: 'number',
    hierarchy4ID: 'number',
    hierarchy5ID: 'number',
    measureUnitsID: 'number',
    leaseCurrencyID: 'number',
    leaseCurrencyISO: 'string',
    tenantLegalName: 'string',
    accountingType: 'string',
    landLordName: 'string',
    leaseTenantHierarchyID: 'number',
    buildingArchivedByID: 'number',
    buildingArchivedBy: 'string',
    buildingArchivedDate: 'Date',
    buildingCreatedDate: 'Date',
    leaseArchivedByID: 'number',
    leaseArchivedBy: 'string',
    leaseArchivedDate: 'Date',
    leaseCreatedDate: 'Date',
    leaseModifiedDate: 'Date',
    leaseActive: 'boolean',
    leaselabel: 'string',
    accountingWorkFlowStatusStep: 'number',
    accountingWorkFlowStatusID: 'number',
    accountingWorkFlowStatusDisplay: 'string',
    accountingWorkFlowStatus: 'string',
    cachedDate: 'Date',
    leaseAllocationDisplay1: 'string',
    leaseAllocationDisplay2: 'string',
    leaseAllocationDisplayString: 'string',
    leaseAllocationDisplayString2: 'string',
    systemLeaseID: 'number',
    leaseVerificationStatus: 'string',
    hierarchyLevel1: 'string',
    hierarchyLevel2: 'string',
    hierarchyLevel3: 'string',
    hierarchyLevel4: 'string',
    hierarchyLevel5: 'string',
    equipmentType: 'string',
  },
  Periods: {
    accountingPeriodID: 'number',
    leaseAbstractID: 'number',
    isActive: 'boolean',
    isPublished: 'boolean',
    accountingEventID: 'number',
    accountingEventMasterID: 'number',
    systemLeaseID: 'number',
    portfolioID: 'number',
    portfolio: 'string',
    calendarID: 'number',
    chargeTypeFactor: 'currency',
    displayPeriod: 'string',
    periodYearMonth: 'number',
    periodYearQuarter: 'number',
    periodBegin: 'Date',
    periodEnd: 'Date',
    periodEvent: 'string',
    periodIndex: 'number',
    periodMonth: 'number',
    periodQuarter: 'number',
    periodYear: 'number',
    priorPeriod: 'number',
    daysInFullPeriod: 'number',
    actualDaysInPeriod: 'number',
    remainingTermInMonths: 'number',
    accountingEventIndex: 'number',
    isBeginningBalance: 'boolean',
    isLastPeriod: 'boolean',
    isLiabilityMatured: 'boolean',
    accountingEventJEProcessingStatus: 'string',
    accountingPeriodJEProcessingStatus: 'string',
    accountingPeriodJEProcessingStatusOrder: 'number',
    approvedByID: 'number',
    approvedBy: 'string',
    approvedDate: 'Date',
    exportClientBatchNumber: 'string',
    exportedByID: 'number',
    exportedBy: 'string',
    exportedDate: 'Date',
    exportSystemBatchNumber: 'number',
    scheduledPayments: 'currency',
    remainingPayments: 'currency',
    cumulativeScheduledPayments: 'currency',
    straightLineExpense: 'currency',
    straightLineIncome: 'currency',
    straightLineExpenseDaily: 'currency',
    straightLineIncomeDaily: 'currency',
    deferredLeaseExpense: 'currency',
    deferredLeaseExpenseBalance: 'currency',
    deferredLeaseReceivable: 'currency',
    deferredRentReceivableBalance: 'currency',
    cumulativeDeferredLeaseExpense: 'currency',
    cumulativeDeferredRentReceivable: 'currency',
    cumulativeAdjustments: 'currency',
    shortTermDeferredRentReceivable: 'currency',
    longTermDeferredRentReceivable: 'currency',
    cumulativeStraightLineExpense: 'currency',
    cumulativeStraightLineIncome: 'currency',
    depreciationExpense: 'currency',
    cumulativeDepreciationExpense: 'currency',
    initialBeginningAssetBalance: 'currency',
    assetBalanceOpening: 'currency',
    assetBalanceClosing: 'currency',
    assetAmortization: 'currency',
    accumulatedAssetAmortization: 'currency',
    totalAssetAdjustment: 'currency',
    manualAssetAdjustment: 'currency',
    manualAssetAdjustmentImpairment: 'currency',
    systemAssetAdjustment: 'currency',
    terminationFee: 'currency',
    directCosts: 'currency',
    adjustmentGainLoss: 'currency',
    cumulativeAssetAdjustment: 'currency',
    assetAdjustmentCPICumulativeCapReached: 'currency',
    assetAdjustmentDataCorrection: 'currency',
    assetAdjustmentFullTermination: 'currency',
    assetAdjustmentImpairment: 'currency',
    assetAdjustmentInitial: 'currency',
    assetAdjustmentOther: 'currency',
    assetAdjustmentPartialTermination: 'currency',
    assetAdjustmentRenewal: 'currency',
    assetAdjustmentRentReview: 'currency',
    assetAdjustmentTermination: 'currency',
    levelExpense: 'currency',
    cumulativeLevelExpense: 'currency',
    initialBeginningLiabilityBalance: 'currency',
    liabilityBalanceOpening: 'currency',
    liabilityBalanceClosing: 'currency',
    liabilityReduction: 'currency',
    cumulativeLiabilityReduction: 'currency',
    leaseLiabilityInterestExpense: 'currency',
    cumulativeLeaseLibilityInterestExpense: 'currency',
    liabilityAdjustment: 'currency',
    cumulativeLiabilityAdjustment: 'currency',
    liabilityAdjustmentCPICumulativeCapReached: 'currency',
    liabilityAdjustmentDataCorrection: 'currency',
    liabilityAdjustmentFullTermination: 'currency',
    liabilityAdjustmentImpairment: 'currency',
    liabilityAdjustmentInitial: 'currency',
    liabilityAdjustmentOther: 'currency',
    liabilityAdjustmentPartialTermination: 'currency',
    liabilityAdjustmentRenewal: 'currency',
    liabilityAdjustmentRentReview: 'currency',
    liabilityAdjustmentTermination: 'currency',
    shortTermLiabilityOpening: 'currency',
    shortTermLiabilityClosing: 'currency',
    shortTermLiabilityAdjustment: 'currency',
    shortTermLiabilityReduction: 'currency',
    longTermLiabilityClosing: 'currency',
    longTermLiabilityAdjustment: 'currency',
    longTermLiabilityOpening: 'currency',
    longTermLiabilityReduction: 'currency',
    grossInvestmentOpening: 'currency',
    grossInvestmentClosing: 'currency',
    earnedIncome: 'currency',
    unearnedIncome: 'currency',
    investmentAdjustment: 'currency',
    investmentReductions: 'currency',
    accumulatedInvestmentReduction: 'currency',
    cumulativeEarnedIncome: 'currency',
    cumulativeNetInvestInLeaseReceivableReduction: 'currency',
    currentPortionOfInvestment: 'currency',
    currentPortionUnearnedIncome: 'currency',
    netInvestmentInLeaseReceivableOpening: 'currency',
    netInvestmentInLeaseReceivableClosing: 'currency',
    netInvestmentInLeaseReceivableAdjustment: 'currency',
    netInvestmentInLeaseReceivableReduction: 'currency',
    shortTermNetInvestmentInLeaseReceivableOpening: 'currency',
    shortTermNetInvestmentInLeaseReceivableClosing: 'currency',
    shortTermNetInvestmentInLeaseReceivableAdjustment: 'currency',
    shortTermNetInvestmentInLeaseReceivableReduction: 'currency',
    longTermNetInvestmentInLeaseReceivableOpening: 'currency',
    longTermNetInvestmentInLeaseReceivableClosing: 'currency',
    longTermNetInvestmentInLeaseReceivableAdjustment: 'currency',
    longTermNetInvestmentInLeaseReceivableReduction: 'currency',
    measureEvent: 'string',
    measureEventID: 'number',
    isImpaired: 'boolean',
    localCurrencyDecimalPrecision: 'number',
    localCurrencyISO: 'string',
    localCurrencyID: 'number',
    initialBeginningAssetBalanceFunctional: 'currency',
    modificationImpactsScope: 'boolean',
    reconcileAccountAccumAsset: 'string',
    reconcileAccountFunctionalAccumAsset: 'string',
    reconcileAccountShortTermLiability: 'string',
    reconcileAccountLongTermLiability: 'string',
    reconcileAccountDepreciation: 'string',
    isLocked: 'boolean',
    batchID: 'number',
    parentScheduleID: 'number',
    grossAssetBalance: 'currency',
    isReportingException: 'boolean',
    exceptionReason: 'string',
    amortizationProfileID: 'number',
    amortizationProfile: 'string',
    journalEntryProfileID: 'number',
    journalEntryProfile: 'string',
    isRetroAdjust: 'boolean',
    classificationName: 'string',
    classificationID: 'number',
    accountingEventBeginDate: 'Date',
    accountingEventEndDate: 'Date',
    paymentTiming: 'string',
    discountRate: 'number',
    annualRateType: 'string',
    functionalCurrencyID: 'number',
    functionalCurrencyRate: 'number',
    functionalCurrencyISO: 'string',
    functionalInitialBeginningAssetBalance: 'currency',
    functionalAssetBalanceOpening: 'currency',
    functionalAssetBalanceClosing: 'currency',
    functionalAssetAmortization: 'currency',
    functionalAccumulatedAssetAmortization: 'currency',
    functionalTotalAssetAdjustment: 'currency',
    functionalROUAssetInterestExpense: 'currency',
    functionalManualAssetAdjustment: 'currency',
    functionalManualAssetAdjustmentImpairment: 'currency',
    functionalSystemAssetAdjustment: 'currency',
    functionalTerminationFee: 'currency',
    functionalDirectCosts: 'currency',
    functionalAdjustmentGainLoss: 'currency',
    functionalAssetAdjustmentCPICumulativeCapReached: 'currency',
    functionalAssetAdjustmentDataCorrection: 'currency',
    functionalAssetAdjustmentFullTermination: 'currency',
    functionalAssetAdjustmentImpairment: 'currency',
    functionalAssetAdjustmentInitial: 'currency',
    functionalAssetAdjustmentOther: 'currency',
    functionalAssetAdjustmentPartialTermination: 'currency',
    functionalAssetAdjustmentRenewal: 'currency',
    functionalAssetAdjustmentRentReview: 'currency',
    functionalAssetAdjustmentTermination: 'currency',
    functionalLevelExpense: 'currency',
    cachedDate: 'Date',
    isQuarterBegin: 'boolean',
    isQuarterEnd: 'boolean',
    isYearBegin: 'boolean',
    isYearEnd: 'boolean',
    // Fields from the lease side below
    leaseSourceImportID: 'string',
    leaseObjectTypeTypeID: 'number',
    leaseTemplate: 'string',
    leaseTemplateBillingType: 'string',
    leaseTemplateBillingTypeID: 'number',
    calendar: 'string',
    buildingID: 'number',
    buildingSourceImportID: 'string',
    buildingStatus: 'boolean',
    buildingObjectTypeTypeID: 'number',
    buildingTemplate: 'string',
    buildingTemplateBillingType: 'string',
    buildingTemplateBillingTypeID: 'number',
    premiseID: 'number',
    systemLeaseStatus: 'string',
    clientLeaseID: 'string',
    ownershipType: 'string',
    buildingName: 'string',
    leaseName: 'string',
    leaseDisplayString: 'string',
    address1: 'string',
    address2: 'string',
    city: 'string',
    stateName: 'string',
    zipCode: 'string',
    country: 'string',
    buildingTypeID: 'number',
    buildingType: 'string',
    buildingRentableArea: 'number',
    buildingMeasureUnits: 'string',
    buildingSF: 'number',
    buildingSM: 'number',
    buildingHierarchyID: 'number',
    leaseHierarchyID: 'number',
    leaseStatus: 'string',
    leaseStatusID: 'number',
    currentCommencementDate: 'Date',
    currentExpirationDate: 'Date',
    remainingLeaseTerminYears: 'number',
    leaseRentableArea: 'number',
    leaseMeasureUnits: 'string',
    leaseSF: 'number',
    leaseSM: 'number',
    hierarchy: 'string',
    hierarchy1ID: 'number',
    hierarchy2ID: 'number',
    hierarchy3ID: 'number',
    hierarchy4ID: 'number',
    hierarchy5ID: 'number',
    measureUnitsID: 'number',
    leaseCurrencyID: 'number',
    leaseCurrencyISO: 'string',
    tenantLegalName: 'string',
    accountingType: 'string',
    landLordName: 'string',
    leaseTenantHierarchyID: 'number',
    buildingArchivedByID: 'number',
    buildingArchivedBy: 'string',
    buildingArchivedDate: 'Date',
    buildingCreatedDate: 'Date',
    leaseArchivedByID: 'number',
    leaseArchivedBy: 'string',
    leaseArchivedDate: 'Date',
    leaseCreatedDate: 'Date',
    leaseModifiedDate: 'Date',
    leaseActive: 'boolean',
    leaselabel: 'string',
    accountingWorkFlowStatusStep: 'number',
    accountingWorkFlowStatusID: 'number',
    accountingWorkFlowStatusDisplay: 'string',
    accountingWorkFlowStatus: 'string',
    leaseAllocationDisplay1: 'string',
    leaseAllocationDisplay2: 'string',
    leaseAllocationDisplayString: 'string',
    leaseAllocationDisplayString2: 'string',
    leaseVerificationStatus: 'string',
    hierarchyLevel1: 'string',
    hierarchyLevel2: 'string',
    hierarchyLevel3: 'string',
    hierarchyLevel4: 'string',
    hierarchyLevel5: 'string',
    equipmentType: 'string',
  },
  Alerts: {
    //tblLeaseAlert
    leaseAlertID: 'number',
    alertRuleID: 'number',
    masterGroupID: 'number',
    leaseAbstractID: 'number',
    leaseRecognitionScheduleID: 'number',
    gLEventID: 'number',
    gLEventSource: 'string',
    leaseRecognitionPeriodID: 'number',
    createdDate: 'Date',
    alertInformation: 'string',
    alertExpectedValue: 'number',
    alertActualValue: 'number',
    alertRecommendedAction: 'string',
    alertCheckSum: 'number',
    isDismissed: 'boolean',
    modified: 'Date',
    modifiedBy: 'number',
    dismissReason: 'string',

    //tblAlertType
    alertTypeID: 'number',
    alertType: 'string',
    alertTypeDescription: 'string',

    //tblAlertRule
    legacyExceptionID: 'number',
    objectTypeID: 'number',
    ruleName: 'string',
    ruleDescription: 'string',
    ruleCode: 'string',
    alertRuleSeverityID: 'number',
    isDismissable: 'boolean',
    isActive: 'boolean',
    ruleSQL: 'string',
    lastRunTime: 'Date',

    //tblAlertRuleSeverity
    ruleSeverityLevel: 'number',
    ruleSeverityName: 'string',
    ruleSeverityDescription: 'string',

    //tblReportingLeases
    leaseSourceImportID: 'string',
    leaseObjectTypeTypeID: 'number',
    leaseTemplate: 'string',
    leaseTemplateBillingType: 'string',
    leaseTemplateBillingTypeID: 'number',
    portfolio: 'string',
    portfolioID: 'number',
    calendar: 'string',
    calendarID: 'number',
    buildingID: 'number',
    buildingSourceImportID: 'string',
    buildingStatus: 'boolean',
    buildingObjectTypeTypeID: 'number',
    buildingTemplate: 'string',
    buildingTemplateBillingType: 'string',
    buildingTemplateBillingTypeID: 'number',
    premiseID: 'number',
    systemLeaseStatus: 'string',
    clientLeaseID: 'string',
    ownershipType: 'string',
    buildingName: 'string',
    leaseName: 'string',
    leaseDisplayString: 'string',
    address1: 'string',
    address2: 'string',
    city: 'string',
    stateName: 'string',
    zipCode: 'string',
    country: 'string',
    buildingTypeID: 'number',
    buildingType: 'string',
    buildingRentableArea: 'number',
    buildingMeasureUnits: 'string',
    buildingSF: 'number',
    buildingSM: 'number',
    buildingHierarchyID: 'number',
    leaseHierarchyID: 'number',
    leaseStatus: 'string',
    leaseStatusID: 'number',
    currentCommencementDate: 'Date',
    currentExpirationDate: 'Date',
    remainingLeaseTerminYears: 'number',
    leaseRentableArea: 'number',
    leaseMeasureUnits: 'string',
    leaseSF: 'number',
    leaseSM: 'number',
    hierarchy: 'string',
    hierarchy1ID: 'number',
    hierarchy2ID: 'number',
    hierarchy3ID: 'number',
    hierarchy4ID: 'number',
    hierarchy5ID: 'number',
    measureUnitsID: 'number',
    leaseCurrencyID: 'number',
    leaseCurrencyISO: 'string',
    tenantLegalName: 'string',
    accountingType: 'string',
    landLordName: 'string',
    leaseTenantHierarchyID: 'number',
    buildingArchivedByID: 'number',
    buildingArchivedBy: 'string',
    buildingArchivedDate: 'Date',
    buildingCreatedDate: 'Date',
    leaseArchivedByID: 'number',
    leaseArchivedBy: 'string',
    leaseArchivedDate: 'Date',
    leaseCreatedDate: 'Date',
    leaseModifiedDate: 'Date',
    leaseActive: 'boolean',
    leaselabel: 'string',
    accountingWorkFlowStatusStep: 'number',
    accountingWorkFlowStatusID: 'number',
    accountingWorkFlowStatusDisplay: 'string',
    accountingWorkFlowStatus: 'string',
    cachedDate: 'Date',
    leaseAllocationDisplay1: 'string',
    leaseAllocationDisplay2: 'string',
    leaseAllocationDisplayString: 'string',
    leaseAllocationDisplayString2: 'string',
    systemLeaseID: 'number',
    leaseVerificationStatus: 'string',
    hierarchyLevel1: 'string',
    hierarchyLevel2: 'string',
    hierarchyLevel3: 'string',
    hierarchyLevel4: 'string',
    hierarchyLevel5: 'string',
    equipmentType: 'string',
  },
};
