import { NgModule } from "@angular/core";

import {
  DevExtremeModule,
  DxChartModule,
  DxCircularGaugeModule,
  DxDataGridModule,
  DxDateBoxModule,
  DxDropDownButtonModule,
  DxFileManagerModule,
  DxFormModule,
  DxHtmlEditorModule,
  DxListModule,
  DxPivotGridModule,
  DxPopupModule,
  DxRangeSliderModule,
  DxScrollViewModule,
  DxSelectBoxModule,
  DxTabsModule,
  DxTemplateModule,
  DxTextAreaModule,
  DxToastModule,
  DxTreeViewModule,
} from 'devextreme-angular';


@NgModule({
  imports: [
    DevExtremeModule,
    DxChartModule,
    DxCircularGaugeModule,
    DxDataGridModule,
    DxDateBoxModule,
    DxDropDownButtonModule,
    DxFileManagerModule,
    DxFormModule,
    DxHtmlEditorModule,
    DxListModule,
    DxPivotGridModule,
    DxPopupModule,
    DxRangeSliderModule,
    DxScrollViewModule,
    DxSelectBoxModule,
    DxTabsModule,
    DxTemplateModule,
    DxTextAreaModule,
    DxToastModule,
    DxTreeViewModule,
  ],
  exports: [
    DevExtremeModule,
    DxChartModule,
    DxCircularGaugeModule,
    DxDataGridModule,
    DxDateBoxModule,
    DxDropDownButtonModule,
    DxFileManagerModule,
    DxFormModule,
    DxHtmlEditorModule,
    DxListModule,
    DxPivotGridModule,
    DxPopupModule,
    DxRangeSliderModule,
    DxScrollViewModule,
    DxSelectBoxModule,
    DxTabsModule,
    DxTemplateModule,
    DxTextAreaModule,
    DxToastModule,
    DxTreeViewModule,
  ]
})
export class DevExpressModule { }
