export class Clause {
    id : number;
	clauseType : string;
	clause : string;
	name : string;

	constructor( id, clauseType, clause, name ) {
		this.id = id;
		this.clauseType = clauseType;
		this.clause = clause;	
		this.name = name;		
	}
}

export let clauses : Clause[] = [
	new Clause(1, 'insurance', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce eget mauris ac ante molestie aliquet nec in dolor. Nulla ut finibus leo, quis feugiat diam. Ut auctor aliquet nulla in gravida. Cras in nisi tempus, ullamcorper eros at, consectetur justo. Curabitur quis fermentum leo. Donec sollicitudin elit urna. Morbi accumsan commodo lectus, vitae facilisis nulla volutpat ac', 'Default'),
	new Clause(2, 'insurance', 'Fusce id semper nisi. Curabitur dictum laoreet arcu eu porta. Mauris pretium finibus pulvinar. Aliquam sed congue dui. Donec ut nunc lacinia, rhoncus odio ut, tempor quam. Morbi sagittis ante vel sem bibendum tristique.', 'Landlord Insurance'),
	new Clause(3, 'opex', 'Vestibulum feugiat sit amet nibh eu suscipit. Nam finibus pellentesque felis nec aliquam. Aliquam pellentesque vulputate justo a blandit. Praesent ut tortor consectetur, pretium metus ut, mattis justo. Aliquam scelerisque pellentesque pulvinar. Vestibulum nec lacinia leo. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.', 'Default'),
	new Clause(4, 'parking', 'Duis porta enim quis lorem aliquet commodo. Nullam rutrum mauris nibh, sit amet viverra justo hendrerit eget. Maecenas a tortor non nisi convallis aliquet et ac lectus. Quisque sed dolor finibus, porta nibh vel, aliquet massa. ', 'Default'),
	new Clause(5, 'parking', 'Sed est mi, iaculis sodales felis porttitor, blandit scelerisque nisi. Duis ut turpis elit. Cras id elementum leo. Nulla sollicitudin est mattis malesuada aliquam. Sed quis mauris ac dolor convallis congue. Vestibulum ullamcorper blandit orci, sed tristique tortor bibendum id.', 'No Parking'),
	new Clause(7, 'opex', 'Proin vitae faucibus enim, et facilisis magna. Vestibulum ullamcorper tempus dictum. Sed justo erat, mollis id ornare varius, bibendum vel ante. Aliquam mi nibh, faucibus at tempor ut, condimentum nec neque.', 'California'),
	new Clause(8, 'retaxes', 'Ut magna orci, auctor a libero et, laoreet egestas leo. Nulla tincidunt porta lorem, vitae gravida odio interdum ac. Suspendisse potenti. Mauris placerat, sapien non semper viverra, leo odio rhoncus quam, eu varius lorem dolor vel sapien. Suspendisse rutrum efficitur augue et tincidunt. ', 'Default'),
	new Clause(9, 'retaxes', 'Ut risus enim, commodo non enim eu, feugiat gravida orci. Nam non quam fermentum, cursus magna quis, suscipit eros. Phasellus in tempor leo. Duis tempor at ipsum nec ullamcorper. Maecenas pellentesque velit non quam feugiat fermentum.', 'RE Taxes'),
	new Clause(10, 'utilities', 'Vivamus in elementum dolor. Mauris congue semper ante vel luctus. Suspendisse lorem tellus, placerat vestibulum eleifend id, venenatis a libero. Interdum et malesuada fames ac ante ipsum primis in faucibus.', 'Default'),
	new Clause(11, 'alterations', 'Donec aliquet, neque ac feugiat ultricies, ex sem sodales elit, a ullamcorper magna tellus interdum ipsum. In imperdiet quis ligula non finibus. Vestibulum vulputate, lorem vel sollicitudin cursus, nisi est elementum nunc, vitae vulputate nisi massa in leo.', 'Utilities'),
	new Clause(12, 'utilities', 'Donec finibus maximus velit, at sodales ligula semper varius. Aenean erat risus, sollicitudin eu metus nec, dignissim hendrerit ligula.', 'Default'),
	new Clause(13, 'assignment', 'In dapibus massa et odio laoreet, nec ornare turpis iaculis. Etiam id lectus ac eros scelerisque finibus. Donec cursus arcu ultricies venenatis pharetra. Sed eget tortor id sapien tempor tristique sodales ac turpis. Vestibulum tincidunt id tellus ut sagittis.', 'Default'),
	new Clause(14, 'assignment', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus eget sapien et urna malesuada condimentum condimentum ac quam. Quisque vehicula interdum lorem sed tincidunt.', 'Assignment'),
	new Clause(15, 'estoppel', 'Integer eu dapibus nunc, sit amet feugiat enim. In sit amet efficitur nisi. Mauris vehicula nunc molestie hendrerit volutpat. Cras magna massa, venenatis rhoncus dapibus sit amet, tincidunt nec sem. Aenean maximus augue et neque aliquet viverra. Nullam nec risus eu erat auctor euismod.', 'Default'),
	new Clause(16, 'estoppel', 'Pellentesque non lobortis leo. Donec non vehicula ipsum, in aliquam lectus. Donec ultrices neque nunc, eget pretium ex laoreet at. ', 'Estoppel'),
	new Clause(17, 'holdover', 'Morbi nisl arcu, vestibulum maximus tortor quis, rutrum consectetur urna. Phasellus hendrerit leo leo, id iaculis enim dapibus fringilla. Aenean id felis purus. Quisque a venenatis felis. Cras mauris leo, tincidunt vitae lacus eu, faucibus condimentum nunc.', 'Default'),
	new Clause(18, 'holdover', 'Nullam sollicitudin efficitur tortor, quis sollicitudin risus luctus sed. Aenean vitae auctor nibh. Vestibulum suscipit augue a luctus mattis. Sed quis metus fringilla, lobortis nisl ut, condimentum erat.', 'Holdover'),
	new Clause(19, 'hoursofoperation', 'Suspendisse lacinia odio nulla. Suspendisse interdum quam eu ultricies consequat. In ultrices pretium augue, et consequat dolor venenatis sit amet. Proin ut orci molestie, finibus velit nec, pellentesque urna. Nulla viverra nunc metus, nec tincidunt arcu efficitur eget.', 'Default'),
	new Clause(20, 'hoursofoperation', 'Praesent aliquam augue risus, eu volutpat sem blandit quis. Quisque aliquam, arcu vitae venenatis pellentesque, purus dolor pellentesque metus, vel ornare tortor elit euismod magna.', 'Hours of Operation'),
	new Clause(21, 'latefee', 'Integer tincidunt vestibulum pretium. Etiam consectetur, ex sit amet cursus scelerisque, orci ipsum viverra nulla, quis posuere massa nibh eu nisl. ', 'Default'),
	new Clause(22, 'latefee', 'Ut faucibus erat et erat finibus, ut viverra eros porta. Nunc condimentum dictum augue vel pellentesque. Integer malesuada interdum tempor. ', 'Late Fee'),
	new Clause(23, 'permitteduse', 'Maecenas blandit massa nulla, hendrerit facilisis augue molestie sit amet. In metus quam, maximus in cursus id, tempor eu felis. Maecenas id nunc vel nibh congue finibus. Curabitur turpis ipsum, scelerisque sed suscipit ac, porta eget justo.', 'Default'),
	new Clause(24, 'permitteduse', 'Morbi dapibus luctus arcu, sit amet commodo elit. Duis felis purus, fermentum sed ornare pharetra, feugiat eget metus. Duis finibus porttitor enim ac semper.', 'Permitted Use'),
	new Clause(25, 'signage', 'Donec eu arcu arcu. In laoreet justo non urna molestie luctus. Vestibulum et sapien lorem. Integer consectetur id massa vitae egestas. ', 'Default'),
	new Clause(26, 'signage', 'Curabitur pellentesque leo augue, et bibendum lectus porttitor in. Pellentesque ac efficitur arcu. In facilisis risus vitae suscipit egestas. Nulla facilisi. Aenean ornare ultrices maximus. Suspendisse faucibus scelerisque nulla, ut faucibus nulla luctus non.', 'Signage'),
	new Clause(27, 'surrender', 'Maecenas et nulla non lacus accumsan imperdiet sit amet quis sapien. Aenean ut suscipit nibh. Proin blandit sodales lorem eu luctus. Aliquam vitae dolor pretium, bibendum nisl sed, dignissim neque. ', 'Default'),
	new Clause(28, 'surrender', 'Praesent ut ante quis augue hendrerit viverra. Integer suscipit ipsum et sem aliquam, quis faucibus dui malesuada. Morbi volutpat tempor dui, vitae rhoncus nisi.', 'Surrencer'),
	new Clause(29, 'insurance', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce eget mauris ac ante molestie aliquet nec in dolor. Nulla ut finibus leo, quis feugiat diam. Ut auctor aliquet nulla in gravida. Cras in nisi tempus, ullamcorper eros at, consectetur justo. Curabitur quis fermentum leo. Donec sollicitudin elit urna. Morbi accumsan commodo lectus, vitae facilisis nulla volutpat ac', 'Default'),
	new Clause(30, 'insurance', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce eget mauris ac ante molestie aliquet nec in dolor. Nulla ut finibus leo, quis feugiat diam. Ut auctor aliquet nulla in gravida. Cras in nisi tempus, ullamcorper eros at, consectetur justo. Curabitur quis fermentum leo. Donec sollicitudin elit urna. Morbi accumsan commodo lectus, vitae facilisis nulla volutpat ac', 'Default'),
	new Clause(31, 'insurance', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce eget mauris ac ante molestie aliquet nec in dolor. Nulla ut finibus leo, quis feugiat diam. Ut auctor aliquet nulla in gravida. Cras in nisi tempus, ullamcorper eros at, consectetur justo. Curabitur quis fermentum leo. Donec sollicitudin elit urna. Morbi accumsan commodo lectus, vitae facilisis nulla volutpat ac', 'Default'),
	new Clause(32, 'insurance', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce eget mauris ac ante molestie aliquet nec in dolor. Nulla ut finibus leo, quis feugiat diam. Ut auctor aliquet nulla in gravida. Cras in nisi tempus, ullamcorper eros at, consectetur justo. Curabitur quis fermentum leo. Donec sollicitudin elit urna. Morbi accumsan commodo lectus, vitae facilisis nulla volutpat ac', 'Default'),
	new Clause(33, 'insurance', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce eget mauris ac ante molestie aliquet nec in dolor. Nulla ut finibus leo, quis feugiat diam. Ut auctor aliquet nulla in gravida. Cras in nisi tempus, ullamcorper eros at, consectetur justo. Curabitur quis fermentum leo. Donec sollicitudin elit urna. Morbi accumsan commodo lectus, vitae facilisis nulla volutpat ac', 'Default'),
	new Clause(34, 'insurance', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce eget mauris ac ante molestie aliquet nec in dolor. Nulla ut finibus leo, quis feugiat diam. Ut auctor aliquet nulla in gravida. Cras in nisi tempus, ullamcorper eros at, consectetur justo. Curabitur quis fermentum leo. Donec sollicitudin elit urna. Morbi accumsan commodo lectus, vitae facilisis nulla volutpat ac', 'Default'),
	new Clause(35, 'insurance', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce eget mauris ac ante molestie aliquet nec in dolor. Nulla ut finibus leo, quis feugiat diam. Ut auctor aliquet nulla in gravida. Cras in nisi tempus, ullamcorper eros at, consectetur justo. Curabitur quis fermentum leo. Donec sollicitudin elit urna. Morbi accumsan commodo lectus, vitae facilisis nulla volutpat ac', 'Default'),
	new Clause(36, 'insurance', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce eget mauris ac ante molestie aliquet nec in dolor. Nulla ut finibus leo, quis feugiat diam. Ut auctor aliquet nulla in gravida. Cras in nisi tempus, ullamcorper eros at, consectetur justo. Curabitur quis fermentum leo. Donec sollicitudin elit urna. Morbi accumsan commodo lectus, vitae facilisis nulla volutpat ac', 'Default'),
	new Clause(37, 'insurance', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce eget mauris ac ante molestie aliquet nec in dolor. Nulla ut finibus leo, quis feugiat diam. Ut auctor aliquet nulla in gravida. Cras in nisi tempus, ullamcorper eros at, consectetur justo. Curabitur quis fermentum leo. Donec sollicitudin elit urna. Morbi accumsan commodo lectus, vitae facilisis nulla volutpat ac', 'Default'),
	new Clause(38, 'insurance', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce eget mauris ac ante molestie aliquet nec in dolor. Nulla ut finibus leo, quis feugiat diam. Ut auctor aliquet nulla in gravida. Cras in nisi tempus, ullamcorper eros at, consectetur justo. Curabitur quis fermentum leo. Donec sollicitudin elit urna. Morbi accumsan commodo lectus, vitae facilisis nulla volutpat ac', 'Default'),
];	