export class Project {
	id : Number;
	name : String;
	type : String;
	projectManager : String;
	status : String;
	targetCompletionDate : String;
	city : String;
	state : String;
	country : String;
	portfolio : String;
	anothercountry : String;
	startDate : String;
	daysActive : String;
	daysToComplete : String;
	clientProjectId : String;
	lastStatusNote : String;
	lastApprovalNote : String;
	systemPercentComplete : String;
	activeTask : String;
	isNew : Boolean;
	isAtRisk : Boolean;
	isOverdue : Boolean;

	constructor(id, name, type, projectManager, status, targetCompletionDate, city, state, country, portfolio, anothercountry, startDate, daysActive, daysToComplete, clientProjectId, lastStatusNote, lastApprovalNote, systemPercentComplete, activeTask, isNew, isAtRisk, isOverdue) {
		this.id = id;
		this.name = name;
		this.type = type;
		this.projectManager = projectManager;
		this.status = status;
		this.targetCompletionDate = targetCompletionDate;
		this.city = city;
		this.state = state;
		this.country = country;
		this.portfolio = portfolio;
		this.anothercountry = anothercountry;
		this.startDate = startDate;
		this.daysActive = daysActive;
		this.daysToComplete = daysToComplete;
		this.clientProjectId = clientProjectId;
		this.lastStatusNote = lastStatusNote;
		this.lastApprovalNote = lastApprovalNote;
		this.systemPercentComplete = systemPercentComplete;
		this.activeTask = activeTask;		
		this.isNew = isNew;
		this.isAtRisk = isAtRisk;
		this.isOverdue = isOverdue;
	}
}

export let projects : Project[] = [
	new Project(3,"USA-GA-Atlanta Renewal","Renewal","John Hancock","Active","8/9/2020","Alpharetta","GA","United States","RE Portfolio","United States","5/19/2020","5916","-5715","internal ID","Decided that this project was going to be too expensive.   Project Cancelled by Real Estate Committee","RE: 4) Site Selection Approved -  Task Completed.  Note Creator:  John Hancock","38",null,true, false, false),
	new Project(7,"USA-IL-Chicago Renewal","Renew","Ben Franklin","Active","8/20/2020","Chicago","IL","United States","RE Portfolio","United States","5/19/2020","1114","-956","CAP-12152012","I added this note at the list page level","RE: 10) Abstract Lease Terms into VirtualPremise Approved -  approved.  Note Creator:  Ben Franklin","38",null,true, false, false),
	new Project(8,"USA-AZ-Phoenix Relocation","Relocation","John Hancock","Active","11/30/2020","Phoenix","AZ","United States","RE Portfolio","United States","5/19/2020","3605",null,"CAP05202010","Relocation complete","RE: 12) Planning and Implementation of Move-in Approved -  Approved.  Note Creator:  John Hancock","8",null,true, false, false),
	new Project(9,"USA-NV-Las Vegas Renewal","Renew","Ben Franklin","Active","6/18/2020","Las Vegas","NV","United States","RE Portfolio",null,"5/19/2020","2509","-1750","CAP-05202010","Sample Status Note","RE: 9) Execution of Sales Contract Approved -  Approved.  Note Creator:  John Hancock","100",null,true, false, false),
	new Project(10,"Atlanta Increase","Analysis","John Hancock","Cancelled","12/1/2020","Atlanta","GA","United States","RE Portfolio",null,"5/19/2020","3605",null,"12345","N/A",null,"0",null,false, false, false),
	new Project(12,"USA-IL-Chicago  (New Purchase)","Analysis","George Washington","Active","10/9/2020",null,"IL","United States","RE Portfolio",null,"5/19/2020","3501","-3220",null,"N/A","RE: 12) Planning and Implementation of Move-in Approved -  Move in complete.  Note Creator:  John Hancock","100",null,true, false, false),
	new Project(13,"USA-GA-Atlanta (Purchase)","Analysis","Samuel Adams","Complete","9/8/15","Atlanta","GA","United States","RE Portfolio",null,"12/1/14","1949","-1668",null,"N/A","RE: 12) Planning and Implementation of Move-in Approved -  Approved.  Note Creator:  John Hancock","88",null,false, true, false),
	new Project(14,"USA-NY-New York (New Office)","Analysis","Paul Revere","Complete","12/8/15","New York","NY","United States","RE Portfolio",null,"5/19/2020","1858","-1577",null,"N/A","RE: 12) Planning and Implementation of Move-in Approved -  Approved.  Note Creator:  John Hancock","75",null,true, true, false),
	new Project(15,"FIN-Helsinki-Helsinki (Office)","Extend","John Hancock","Complete","3/25/14","Helsinki",null,"Finland","RE Portfolio","Finland","3/3/14","2222","-2200","2012","Lease extension complete.  Documents executed and distributed to appropriate departments.","RE: 10) VirtualPremise Updated and Modify Teams as Needed Approved -  Approved.  Note Creator:  John Hancock","100",null,false, false, false),
	new Project(16,"CZE-Stredoceský kraj-Kolin (Mfg)","Renew","Samuel Adams","Complete","3/18/15","Kolin",null,"Czech Republic","RE Portfolio","Czech Republic","3/2/15","1858","-1842",null,"Renewal complete.  Documents executed and lease database has been updated with new dates and rents.","RE: 10) VirtualPremise Updated and Modify Teams as Needed Approved -  Approved.  Note Creator:  John Hancock","100",null,false, false, false),
	new Project(17,"AUS-NSW-Alexandria (Warehouse)","Analysis","Paul Revere","Complete","3/24/15","Alexandria",null,"Australia","RE Portfolio","Australia","3/2/15","1858","-1836",null,"Market study completed","RE: 10) VirtualPremise Updated and Modify Teams as Needed Approved -  Task Completed.  Note Creator:  John Hancock","100",null,false, false, false),
	new Project(18,"USA-GA-Kennesaw (Office)","Extend","Ben Franklin","Complete","2/24/15","Kennesaw","GA","United States","RE Portfolio","United States","2/2/15","1886","-1864",null,"N/A","RE: 9) Documents Distributed Approved -  Approved.  Note Creator:  John Hancock","100",null,false, false, true),
	new Project(19,"CAN-AB-Calgary-Manning Rd (Office)","Sublease","Betsy Ross","Complete","10/31/10","Calgary","AB","Canada","RE Portfolio","Canada","3/1/10","3685","-3441","CAP-10294","N/A","RE: 8) Amendments Executed Approved -  Task Completed.  Note Creator:  John Hancock","100",null,false, false, false),
	new Project(20,"IND--Sahibabad (Mixed Use)","New Lease","Paul Revere","Complete","7/16/15","Sahibabad",null,"India","RE Portfolio","India","3/2/15","1858","-1722",null,"Lease fully executed and business unit has moved in to the space.","RE: 10) Database Updated and Modify Teams as Needed Approved -  Approved.  Note Creator:  John Hancock","100",null,false, false, false),
	new Project(21,"USA-OH-Batavia (Mixed Use)","Site Close","Thomas Jefferson","Future","10/23/15","Batavia","OH","United States","RE Portfolio","United States","10/1/15","1645","-1623",null,"Waiting on direction from business unit to determine if this is a real project.",null,"0",null,false, false, false),
	new Project(22,"POL--Warsaw (Mixed Use)","Site Close","John Hancock","Active","3/24/15","Warsaw",null,"Poland","RE Portfolio","Poland","3/2/15","1858","-1836","31/2011","Early termination option executed.","RE: 10) Lease Database Updated and Modify Teams as Needed Approved -  Update complete.  Note Creator:  John Hancock","10",null,false, false, false),
	new Project(23,"USA-NY-Shirley-Renewal","Renew","George Washington","Active","11/30/15","Shirley","NY","United States","RE Portfolio","United States","5/1/15","1798","-1585",null,"Dir of RE approval to proceed.  Local broker assigned.  Waiting on RFP response from LLs.","RE: 2) Broker Assigned as Appropriate Approved -  Broker assigned.  Note Creator:  John Hancock","20",null,false, false, true),
	new Project(24,"PRI-PR-Guaynabo (Office)","Analysis","John Hancock","Active","11/27/15","Guaynabo",null,"Puerto Rico","RE Portfolio","Puerto Rico","6/1/15","1767","-1588",null,"updated status note","RE: 3) Contact Incumbent LL/Solicit Proposal to Approved -  approved.  Note Creator:  John Hancock","0",null,false, false, false),
	new Project(25,"FRA--Nantes (Office)","Construction","Paul Revere","Active","6/29/17","Nantes",null,"France","RE Portfolio","France","4/1/15","1828","-1008",null,"Build strategy selected.  Waiting on update from architect.","RE: 2) Selection of Build to Suit Strategy Approved -  Strategy defined.  Note Creator:  John Hancock","18",null,false, false, false),
	new Project(26,"AUS-NSW-Sydney (Mixed Use)","Site Close","John Hancock","Future","8/25/15","Sydney",null,"Australia","RE Portfolio","Australia","8/3/15","1704","-1682","smaller space only.","Waiting on direction from business unit execs.",null,"0",null,false, false, false),
	new Project(27,"USA-IL-Champaign (Mixed Use)","Site Close","Martha Washington","Active","9/30/15","Champaign","IL","United States","RE Portfolio","United States","4/1/15","1828","-1646","7/31/12","LL's contacted and RFP documents have been distributed","RE: 5) Corporate Real Estate Approval & Finance Approved -  test.  Note Creator:  John Hancock","40",null,false, false, true),
	new Project(28,"USA-IA-Sumner (Mfg)","New Lease","Evan Test","Active","6/9/15","Sumner","IA","United States","RE Portfolio","United States","12/2/14","1948","-1759",null,"sample note","RE: 9) Documents Distributed Approved -  Approved.  Note Creator:  John Hancock","90",null,false, false, true),
	new Project(29,"BRA-SP-São Paulo-Soares (Mfg)","New Lease","Paul Revere","Active","7/23/15","São Paulo",null,"Brazil","RE Portfolio","Brazil","7/1/15","1737","-1715","space in 2012","RFP documents delivered.  Waiting on responses.","RE: 3) Contact Incumbent LL/Solicit Proposal to Approved -  Approved.  Note Creator:  John Hancock","30",null,false, false, false),
	new Project(30,"MEX-Baja California-Tecate (Warehouse)","Site Close","Martha Washington","Active","1/6/16","Tecate",null,"Mexico","RE Portfolio","Mexico","4/1/15","1828","-1548",null,"Broker assignment complete","RE: 2) Broker Assigned as Appropriate Approved -  Approved.  Note Creator:  John Hancock","22",null,false, false, false),
	new Project(31,"GBR-Essex-Maldon (Mfg)","Sublease","Ben Franklin","Complete","7/23/15","Maldon",null,"United Kingdom","RE Portfolio","United Kingdom","7/1/15","1737","-1715",null,"Request to proceed submitted to RED","RE: 9) Documents Distributed Approved -  this is approved.  Note Creator:  John Hancock","20",null,false, false, false),
	new Project(32,"CHN-Liaoning-Dalian (Office)","Site Close","John Hancock","Complete","1/5/11",null,null,"China","RE Portfolio",null,"3/1/10","3685","-3375",null,"N/A","RE: 9) Execution of Sales Contract Approved -  Approved.  Note Creator:  CoStar  Webinar","100",null,false, false, false),
	new Project(33,"CZE-Ustecky Kraj-Lovosice (Mfg)","Site Close","John Hancock","Cancelled","1/5/11",null,null,"Czech Republic","RE Portfolio",null,"3/1/10","3685","-3375",null,"N/A",null,"0",null,false, false, false),
	new Project(34,"JPN--Tokyo-Machida-shi (Office)","Renew","John Hancock","Active","1/5/16","Tokyo",null,"Japan","RE Portfolio","Japan","6/15/15","1753","-1549",null,"Business unit approval meeting scheduled.","RE: 3) Determine Business Requirements Approved -  approved.  Note Creator:  John Hancock","20",null,false, false, false),
	new Project(35,"CHN-Beijing-Beijing (Office)","Renew","Martha Washington","Active","10/7/15","Beijing",null,"China","RE Portfolio","China","8/31/15","1676","-1639",null,"N/A",null,"0",null,false, false, false),
	new Project(36,"USA-LA-Harahan (Mfg)","Renew","John Hancock","Active","6/9/15","Harahan","LA","United States","RE Portfolio","United States","5/1/15","1798","-1759",null,"N/A",null,"0",null,false, false, false),
	new Project(37,"USA-WA-Redmond (Office)","Renew","Paul Revere","Active","8/6/15","Redmond","WA","United States","RE Portfolio","United States","6/30/15","1738","-1701",null,"N/A",null,"0",null,false, false, true),
	new Project(38,"GBR-West Midlands-Bilston (Office)","Renew","George Washington","Active","12/9/15","Bilston",null,"United Kingdom","RE Portfolio","United Kingdom","11/2/15","1613","-1576",null,"N/A",null,"0",null,false, false, false),
	new Project(39,"USA-LA-Harahan-Jefferson Hwy (Warehouse)","Renew","Betsy Ross","Active","1/6/16","Harahan","LA","United States","RE Portfolio","United States","11/30/15","1585","-1548",null,"N/A",null,"0",null,false, false, false),
	new Project(40,"USA-WA-Federal Way (Office)","Renew","Samuel Adams","Active","11/6/15","Federal Way","WA","United States","RE Portfolio","United States","9/30/15","1646","-1609",null,"Test new Note!!!!!",null,"11",null,false, false, false),
	new Project(41,"CAN-BC-Delta-Chester Rd (Office)","Renew","Paul Revere","Active","10/7/15","Delta","BC","Canada","RE Portfolio","Canada","8/31/15","1676","-1639",null,"N/A",null,"0",null,false, false, false),
	new Project(42,"CAN-MB-Winnipeg (Mixed Use)","Renew","Paul Revere","Active","1/6/16","Winnipeg","SK","Canada","RE Portfolio","Canada","11/30/15","1585","-1548",null,"N/A",null,"0",null,false, false, false),
	new Project(43,"GBR--Milton Keynes-Pitfield (Office)","Renew","Thomas Jefferson","Active","7/7/16","Milton Keynes",null,"United Kingdom","RE Portfolio","United Kingdom","5/31/16","1402","-1365",null,"N/A",null,"0",null,false, false, false),
	new Project(44,"USA-CA-Irwindale (Mfg)","Renew","Thomas Jefferson","Active","4/6/16","Irwindale","CA","United States","RE Portfolio","United States","2/29/16","1494","-1457",null,"N/A",null,"0",null,false, false, false),
	new Project(45,"USA-MN-Roseville (Office)","Renew","Ben Franklin","Active","8/8/16","Roseville","MN","United States","RE Portfolio","United States","6/30/16","1372","-1333",null,"N/A",null,"0",null,false, false, false),
	new Project(46,"CAN-ON-Markham (Mixed Use)","Analysis","George Washington","Active","11/6/15","Markham","MB","Canada","RE Portfolio","Canada","9/30/15","1646","-1609","1145a","N/A",null,"0",null,false, false, false),
	new Project(47,"CAN-BC-Delta-Carleton Court (Office)","Renew","John Hancock","Complete","9/3/10","Delta",null,"India","RE Portfolio","Canada","7/28/10","3536","-3499",null,"N/A","RE: 9) Abstract lease Terms into VirtualPremise Approved -  Approval.  Note Creator:  CoStar  Webinar","100",null,false, false, false),
	new Project(48,"DEU-NRW-Haan (Mixed Use)","Renew","Paul Revere","Active","9/2/15","Haan",null,"Germany","RE Portfolio","Germany","7/27/15","1711","-1674",null,"N/A",null,"0",null,false, false, false),
	new Project(49,"USA-OH-Mayfield Heights (Mixed Use)","Renew","John Hancock","Complete","1/7/15","Mayfield Heights","OH","United States","RE Portfolio","United States","12/1/14","1949","-1912","RR3453","N/A",null,"0",null,false, false, false),
	new Project(50,"PRI--Aguadilla (Mfg)","Renew","Martha Washington","Active","3/9/16","Aguadilla",null,"Puerto Rico","RE Portfolio","Puerto Rico","2/1/16","1522","-1485",null,"N/A",null,"0",null,false, false, false),
	new Project(51,"CHN-Shanghai-Shanghai- Chuangye Rd (Mfg)","Renew","John Hancock","Active","9/3/15","Shanghai",null,"China","RE Portfolio","China","7/28/15","1710","-1673",null,"N/A",null,"0",null,false, false, false),
	new Project(52,"USA-AR-Little Rock (Office)","Renew","John Hancock","Future","12/9/15","Little Rock","AR","United States","RE Portfolio","United States","11/2/15","1613","-1576",null,"N/A",null,"0",null,false, false, false),
	new Project(53,"USA-OR-Wilsonville (Office)","Renew","John Hancock","Active","3/15/13","Wilsonville","OR","United States","RE Portfolio","United States","3/31/10","3655","-2575",null,"N/A",null,"11",null,false, false, false),
	new Project(54,"USA-CA- San Francisco Renewal","Renew","John Hancock","Active","2/8/11",null,"CA","United States","RE Portfolio",null,"12/31/10","3380","-3341",null,"N/A",null,"0",null,false, false, false),
	new Project(55,"BRA-SP-São Paulo-Verbo Divino (Office)","Renew","John Hancock","Active","7/8/15","São Paulo",null,"Brazil","RE Portfolio","Brazil","6/1/15","1767","-1730","C55100","N/A",null,"0",null,false, false, false),
	new Project(56,"CHN-Shanghai-Waigaoqiao (Mixed Use)","Renew","Ben Franklin","Active","11/6/15","Waigaoqiao",null,"China","RE Portfolio","China","9/30/15","1646","-1609",null,"N/A",null,"0",null,false, false, false),
	new Project(57,"TUR-Istanbul-Istanbul (Office)","Renew","John Hancock","Active","11/8/10","Istanbul",null,"Turkey","RE Portfolio","Turkey","9/30/10","3472","-3433",null,"N/A",null,"0",null,false, false, false),
	new Project(58,"CA-ON-Toronto-Dundis Street","Site Close","Betsy Ross","Active","10/23/14","Cambridge","ON","Canada","RE Portfolio","Canada","9/15/13","2391","-1988",null,"N/A","RE: 9) CapEx Approval Approved -  Enter notes here.  Note Creator:  John Hancock","34",null,false, false, false),
	new Project(59,"Lenox Towers - Build out","Construction","John Hancock","Active","2/20/18","Atlanta","GA","United States","RE Portfolio","United States","10/2/13","2374","-772","BLD-125","Project is on hold","RE: 11) Disposition of Existing Real Estate Approved -  123.  Note Creator:  CoStar  Webinar","32",null,false, false, false),
	new Project(64,"USA-CA-SF-Embarcadero-Renewal","Renew","George Washington","Active","7/26/16","San Francisco","CA","United States","RE Portfolio","United States","12/1/14","1949","-1346","CAP-03012012","This is the new blah blha project.  Attachments: Renewal Letter/Embarcadero Renewal Survey.msg","RE: 3) Review LL Default Issues Approved -  Issues reviewed.  Note Creator:  John Hancock","67",null,false, false, false),
	new Project(65,"USA-GA-Atlanta-Lenox Towers Relocation","Relocation","Button Gwinnett","Active","5/30/19","Atlanta","GA","United States","RE Portfolio","United States","12/31/18","458","-308","CAP-01282013a","test status","RE: 2) PHASE 2: DEVELOP ALTERNATIVES Approved -  test.  Note Creator:  CoStar  Webinar","6",null,false, false, false),
	new Project(66,"USA-GA-Atlanta Lenox Tower Build Out","Construction","George Washington","Active","4/5/16","Atlanta","GA","United States","RE Portfolio","United States","11/19/14","1961","-1458","VP-2356","N/A","RE: 2.1) New Task Approved -  Approved.  Note Creator:  John Hancock","54",null,false, false, false),
	new Project(69,"2010 NY 100 Brodway Lobby Renovation","Construction","John Hancock","Complete","8/10/11","New York","NY","United States","RE Portfolio","United States","1/12/10","3733","-3158",null,"N/A",null,"0",null,false, false, false),
	new Project(70,"2011 Teller / IT Upgrade","Construction","John Hancock","Complete","8/9/12","New York","NY","United States","RE Portfolio","United States","1/12/11","3368","-2793",null,"N/A",null,"0",null,false, false, false),
	new Project(76,"USA-NC-Raleigh TI Upgrade","Construction","Betsy Ross","Active","8/22/14",null,"NC","United States","RE Portfolio",null,"5/24/12","2870","-2050",null,"N/A",null,"0",null,false, false, false),
	new Project(79,"USA-CA-San Francisco-Embarcadero New Lease","New Lease","John Hancock","Active","8/14/12","San Francisco","CA","United States","RE Portfolio","United States","7/2/12","2831","-2788","CAPP07020212","N/A","RE: 4.7) Finalize Lease Documents Approved -  Task Coompleted.  Note Creator:  John Hancock","4",null,false, false, false),
	new Project(93,"USA-NC-Raleigh New Lease","New Lease","John Hancock","Cancelled","11/6/12",null,"NC","United States","RE Portfolio",null,"9/5/12","2766","-2704","CAP-1234","N/A",null,"0",null,false, false, false),
	new Project(94,"USA-CA-Fishermans Warf","New Lease","John Hancock","Cancelled","6/4/13",null,"CO","United States","RE Portfolio",null,"9/6/12","2765","-2494","CAP09062012","Project Cancelled. Could not find an appropriate candidate at a reasonable price.",null,"0",null,false, false, false),
	new Project(100,"USA-IL-Naperville (office)L1","New Lease","John Hancock","Active","4/12/13","Naperville","IL","United States","RE Portfolio","United States","10/1/12","2740","-2547","InternID1","N/A","RE: 8) FCA Confirmation and Lease Execution Approved -  Project is complete.  Note Creator:  John Hancock","2",null,false, false, false),
	new Project(103,"USA-NC-Charlotte Tower Building","Site Close","John Hancock","Active","4/26/13","Charlotte","NC","United States","RE Portfolio","United States","11/12/12","2698","-2533",null,"N/A","RE: 10) VirtualPremise Updated and Modify Teams as Needed Approved -  Projected Competed ahead of schedule.  Note Creator:  John Hancock","50",null,false, false, false),
	new Project(107,"US-GA-Atlanta Lenox Towers - Renovations","Construction","John Hancock","Active","2/18/15","Atlanta","GA","United States","RE Portfolio","United States","12/5/12","2675","-1870",null,"N/A",null,"0",null,false, false, false),
	new Project(108,"DFW Terminal C Gate 14 Construction","Construction","John Hancock","Active","10/31/19","Atlanta","TX","United States","RE Portfolio","United States","9/26/13","2380","-154","CAP-9993902X","Updated","RE: 9) PHASE 8:  Budget Reconciliation Approved -  Approved.  Note Creator:  John Hancock","69",null,false, false, false),
	new Project(111,"USA-IL-Chicago Renewal","Renew","Betsy Ross","Active","1/13/16","Chicago","IL","United States","RE Portfolio","United States","12/28/15","1557","-1541","PID: 1229","Preparing for review of existing negotiated terms with business unit exec.","RE: 1) Submit Request to Real Estate Director Approved -  Submitted.  Ned.  Note Creator:  John Hancock","18",null,false, false, false),
	new Project(126,"USA-GA-Norcross-2211 Beaver Ruin","Construction","Betsy Ross","Active","6/29/16","Norcross","GA","United States","RE Portfolio","United States","4/1/14","2193","-1373","DFCS-2014-1","N/A","RE: 5) Gain Control of Selected Sites Approved -  approve.  Note Creator:  John Hancock","42",null,false, false, false),
	new Project(127,"USA-NY-New York - 409 60th Street","New Lease","John Hancock","Active","5/9/13","New York","NY","United States","RE Portfolio","United States","3/11/13","2579","-2520","CAP03948","N/A",null,"0",null,false, false, false),
	new Project(130,"USA-TX-Houston South Houston Frwy","New Lease","Ben Franklin","Complete","2/12/15",null,"TX","United States","RE Portfolio",null,"3/13/14","2212","-1876","CAP-03132013","N/A","RE: 1.7.3) Update project schedule and comments in EE Approved -  approved.  Note Creator:  John Hancock","10",null,false, false, false),
	new Project(131,"USA-TX-San Antonio - TWCT Expansion Site","Extend","John Hancock","Active","10/31/13",null,"TX","United States","RE Portfolio",null,"9/11/13","2395","-2345","CAP091113","N/A","RE: 2.6) Conduct Site Tour Approved -  Done.  Note Creator:  Ben Franklin","35",null,false, false, false),
	new Project(135,"USA-NC-Charlotte Downtown","New Lease","Paul Revere","Active","1/13/16","Concord","NC","United States","RE Portfolio","United States","12/3/14","1947","-1541","CAP-04042013","new status note!!!","RE: 1.5) Receive Approved PIF - Project Initiation Form Approved -  Task Completed.  Note Creator:  Ben Franklin","8",null,false, false, false),
	new Project(139,"USA-GA-Charlotte-New Lease","New Lease","Betsy Ross","Active","4/26/16","Charlotte","NC","United States","RE Portfolio","United States","2/25/15","1863","-1437",null,"N/A","RE: 1) PHASE 1: PROJECT PROJECT INITIATION Approved -  Project Initiation complete.  Note Creator:  John Hancock","6",null,false, false, false),
	new Project(140,"USA-GA--Atlanta Buckhead","New Lease","John Hancock","Active","4/9/14",null,"GA","United States","RE Portfolio",null,"4/26/13","2533","-2185","CAP04252013","N/A","RE: 4) PHASE 4: DOCUMENTATION Approved -  Documentation is complete.  Note Creator:  John Hancock","0",null,false, false, false),
	new Project(153,"USA-CA-Los Angeles North","New Lease","Ben Franklin","Active","5/15/14",null,"CA","United States","RE Portfolio",null,"6/3/13","2495","-2149","345","N/A","RE: 1.1) Review Critical Date Report Approved -  Coompleted on time.  Note Creator:  John Hancock","8",null,false, false, false),
	new Project(156,"USA-FL-Tallahassee Winewood 25K SF Sublet","Site Close","Ben Franklin","Active","8/13/15","Tallahassee","FL","United States","RE Portfolio","United States","7/1/15","1737","-1694",null,"Contact landlord regarding right to terminate the lease early","RE: 5) Corporate Real Estate Approval & Finance Approved -  Approved.  Note Creator:  John Hancock","63",null,false, false, false),
	new Project(159,"USA-GA-Atlanta Phipps Tower","New Lease","Ben Franklin","Complete","11/12/15","Atlanta","GA","United States","RE Portfolio","United States","12/1/14","1949","-1603","Client ID 5555","Comments","RE: 2.6) Conduct Site Tour Approved -  Conducted site tour with local broker and BU exec.  Note Creator:  John Hancock","21",null,false, false, false),
	new Project(167,"Chicago","New Lease","Ben Franklin","Active","5/10/14","Chicago","IL","United States","RE Portfolio","United States","9/4/13","2402","-2154","123","N/A","RE: 4) PHASE 4: DOCUMENTATION Approved -  approved.  Note Creator:  John Hancock","0",null,false, false, false),
	new Project(169,"USA-GA-Atlanta-3438 Phipps","New Lease","George Washington","Complete","2/19/15",null,"GA","United States","RE Portfolio",null,"2/10/15","1878","-1869","CBC-4546","N/A","RE: 2) Move In Week Approved -  Approved.  Note Creator:  John Hancock","100",null,false, false, false),
	new Project(170,"USA-GA-Atlanta - Phipps Tower","New Lease","John Hancock","Active","5/16/18",null,"GA","United States","RE Portfolio",null,"9/10/17","935","-687","CBC-4546","N/A",null,"0",null,false, false, false),
	new Project(181,"Tampa - Lease Renewal","Renew","Paul Revere","Active","11/8/16","Tampa","FL","United States","RE Portfolio","United States","10/25/13","2351","-1241","C2V","Updated project status 10/25/2013","RE: 3) RFP's Submitted Approved -  modified from original move in.  Note Creator:  CoStar  Webinar","33",null,false, false, false),
	new Project(184,"Renew 1213 Main","Renew","John Hancock","Active","10/28/14","Atlanta","GA","United States","RE Portfolio","United States","11/14/13","2331","-1983","CAP 12345","N/A",null,"0",null,false, false, false),
	new Project(193,"Concord NC New Lease","New Lease","John Hancock","Active","2/2/16","Concord","NC","United States","RE Portfolio","United States","2/19/15","1869","-1521",null,"N/A",null,"0",null,false, false, false),
	new Project(195,"LLM - 1123 Woodhil","Construction","John Hancock","Complete","3/11/14","Concord","NC","United States","RE Portfolio","United States","3/5/14","2220","-2214",null,"N/A",null,"0",null,false, false, false),
	new Project(197,"Atlanta - Phipps Tower Renewal","Renew","John Hancock","Active","8/22/19","Atlanta","GA","United States","RE Portfolio","United States","12/17/18","472","-224",null,"N/A",null,"2",null,false, false, false),
	new Project(207,"Orlando Office Remodel","Construction","George Washington","Active","10/26/16","Orlando","FL","United States","RE Portfolio","United States","7/2/14","2101","-1254",null,"Project bid docs delivered to vendors week of 6/15","RE: 3) PHASE 2: Prequalification Approved -  Approved.  Note Creator:  John Hancock","27",null,false, false, false),
	new Project(208,"a","Analysis","CoStar  Webinar","Active","10/12/14","Tecate","a","Mexico","CoStar Real Estate Manager - (Group)","Mexico","10/9/14","2002","-1999",null,"we made a change",null,"0",null,false, false, false),
	new Project(209,"Schwab","Construction","CoStar  Webinar","Active","2/28/17","San Francisco","CA","United States","CoStar Real Estate Manager - (Group)","United States","11/4/14","1976","-1129","1","N/A",null,"0",null,false, false, false),
	new Project(212,"CZE-Stredoceský kraj-Kolin (Mfg) - Lease Expiration","Analysis","CoStar  Webinar","Not Started",null,"Kolin",null,"Czech Republic","ACME CORPORATION, INC.","Czech Republic","1/8/15","1911",null,null,"N/A",null,null,null,false, false, false),
	new Project(213,"CHN-Shanghai-Shanghai-Yu Jia Xi Rd (Mfg) - Lease Expiration","Analysis","CoStar  Webinar","Not Started",null,"Shanghai",null,"China","ACME CORPORATION, INC.","China","1/8/15","1911",null,null,"N/A",null,"0",null,false, false, false),
	new Project(214,"USA-GA-Macon (Office) - Lease Expiration","Analysis","CoStar  Webinar","Not Started",null,"Macon","GA","United States","ACME CORPORATION, INC.","United States","1/8/15","1911",null,null,"N/A",null,null,null,false, false, false),
	new Project(215,"BRA-SP-São Paulo-Ferreira (Office) - Lease Expiration","Analysis","CoStar  Webinar","Not Started",null,"Decatur",null,"Brazil","ACME CORPORATION, INC.","United States","1/8/15","1911",null,null,"N/A",null,null,null,false, false, false),
	new Project(216,"USA-OH-Mayfield Village (Mfg) - Lease Expiration","Analysis","CoStar  Webinar","Not Started",null,"Mayfield Village","OH","United States","ACME CORPORATION, INC.","United States","1/8/15","1911",null,null,"N/A",null,null,null,false, false, false),
	new Project(217,"CHE-Aargau-Aarau-Buchserstrasse (Office) - Lease Expiration","Analysis","CoStar  Webinar","Not Started",null,"Aarau",null,"Switzerland","ACME CORPORATION, INC.","Switzerland","1/8/15","1911",null,null,"N/A",null,null,null,false, false, false),
	new Project(218,"GBR--Milton Keynes-Pitfield (Office) - Lease Expiration","Analysis","CoStar  Webinar","Not Started",null,"Milton Keynes",null,"United Kingdom","ACME CORPORATION, INC.","United Kingdom","1/8/15","1911",null,null,"N/A",null,null,null,false, false, false),
	new Project(219,"USA-GA-Lawrenceville (Mixed Use) - Lease Expiration","Analysis","CoStar  Webinar","Not Started",null,"Lawrenceville","GA","United States","ACME CORPORATION, INC.","United States","1/8/15","1911",null,null,"N/A",null,null,null,false, false, false),
	new Project(220,"DEU-NRW-Wuppertal (Mfg) - Lease Expiration","Analysis","CoStar  Webinar","Not Started",null,"Wuppertal",null,"Germany","ACME CORPORATION, INC.","Germany","1/8/15","1911",null,null,"N/A",null,null,null,false, false, false),
	new Project(221,"CAN-ON-Cambridge-Raglin Pl (Mfg) - Lease Expiration","Analysis","CoStar  Webinar","Not Started",null,"Cambridge","ON","Canada","ACME CORPORATION, INC.","Canada","1/8/15","1911",null,null,"N/A",null,null,null,false, false, false),
	new Project(222,"USA-TN-Memphis (Warehouse) - Lease Expiration","Analysis","CoStar  Webinar","Not Started",null,"Memphis","TN","United States","ACME CORPORATION, INC.","United States","1/8/15","1911",null,null,"N/A",null,null,null,false, false, false),
	new Project(223,"USA-CA-Folsom (Office) - Lease Expiration","Analysis","CoStar  Webinar","Not Started",null,"Folsom","CA","United States","ACME CORPORATION, INC.","United States","1/8/15","1911",null,null,"N/A",null,"0",null,false, false, false),
	new Project(224,"USA-NE-Omaha (Office) - Lease Expiration","Analysis","CoStar  Webinar","Not Started",null,"Omaha","NE","United States","ACME CORPORATION, INC.","United States","1/8/15","1911",null,null,"N/A",null,null,null,false, false, false),
	new Project(225,"USA-MA-Chelmsford (Office) - Lease Expiration","Analysis","CoStar  Webinar","Not Started",null,"Chelmsford","MA","United States","ACME CORPORATION, INC.","United States","1/8/15","1911",null,null,"N/A",null,null,null,false, false, false),
	new Project(226,"CAN-AB-Calgary-Second Ave (Office) - Lease Expiration","Analysis","CoStar  Webinar","Not Started",null,"Calgary","AB","Canada","ACME CORPORATION, INC.","Canada","1/8/15","1911",null,null,"N/A",null,null,null,false, false, false),
	new Project(227,"DEU-Hesse-Frankfurt (Office) - Lease Expiration","Analysis","CoStar  Webinar","Not Started",null,"Frankfurt",null,"Germany","ACME CORPORATION, INC.","Germany","1/8/15","1911",null,null,"N/A",null,null,null,false, false, false),
	new Project(228,"USA-MN-Duluth (Office) - Lease Expiration","Analysis","CoStar  Webinar","Not Started",null,"Duluth","MN","United States","ACME CORPORATION, INC.","United States","1/8/15","1911",null,null,"N/A",null,null,null,false, false, false),
	new Project(229,"USA-IL-Burr Ridge (Office) - Lease Expiration","Analysis","CoStar  Webinar","Not Started",null,"Burr Ridge","IL","United States","ACME CORPORATION, INC.","United States","1/8/15","1911",null,null,"N/A",null,null,null,false, false, false),
	new Project(230,"USA-CO-Golden (Mfg) - Lease Expiration","Analysis","CoStar  Webinar","Not Started",null,"Golden","CO","United States","ACME CORPORATION, INC.","United States","1/8/15","1911",null,null,"N/A",null,"0",null,false, false, false),
	new Project(231,"MYS-Pulau Pinang-Penang (Office) - Lease Expiration","Analysis","CoStar  Webinar","Not Started",null,"Penang",null,"Malaysia","ACME CORPORATION, INC.","Malaysia","1/8/15","1911",null,null,"N/A",null,"0",null,false, false, false),
	new Project(232,"USA-CA-San Jose (Office) - Lease Expiration","Analysis","CoStar  Webinar","Not Started",null,"San Jose","CA","United States","ACME CORPORATION, INC.","United States","1/8/15","1911",null,null,"N/A",null,null,null,false, false, false),
	new Project(233,"MEX-Baja California-Tecate (Warehouse) - Lease Expiration","Analysis","CoStar  Webinar","Not Started",null,"Tecate",null,"Mexico","ACME CORPORATION, INC.","Mexico","1/8/15","1911",null,null,"N/A",null,null,null,false, false, false),
	new Project(234,"ZAF--Capetown (Office) - Lease Expiration","Analysis","CoStar  Webinar","Not Started",null,"Capetown",null,"South Africa","ACME CORPORATION, INC.","South Africa","1/8/15","1911",null,null,"N/A",null,null,null,false, false, false),
	new Project(235,"USA-CA-Mission Viejo (Office) - Lease Expiration","Analysis","CoStar  Webinar","Not Started",null,"Mission Viejo","CA","United States","ACME CORPORATION, INC.","United States","1/8/15","1911",null,null,"N/A",null,null,null,false, false, false),
	new Project(236,"DEU-Hamburg-Hamburg (Office) - Lease Expiration","Analysis","CoStar  Webinar","Not Started",null,"Hamburg",null,"Germany","ACME CORPORATION, INC.","Germany","1/8/15","1911",null,null,"N/A",null,null,null,false, false, false),
	new Project(237,"MEX-Nuevo Leon-Guadalupe (Manufacturing) - Lease Expiration","Analysis","CoStar  Webinar","Not Started",null,"Guadalupe",null,"Mexico","ACME CORPORATION, INC.","Mexico","1/8/15","1911",null,null,"N/A",null,null,null,false, false, false),
	new Project(238,"USA-CO-Highlands Ranch (Office) - Lease Expiration","Analysis","CoStar  Webinar","Not Started",null,"Highlands Ranch","CO","United States","ACME CORPORATION, INC.","United States","1/8/15","1911",null,null,"N/A",null,null,null,false, false, false),
	new Project(239,"USA-FL-Orlando 3965 Silver Star Road - Lease Expiration","Analysis","CoStar  Webinar","Not Started",null,"Orlando","FL","United States","ACME CORPORATION, INC.","United States","1/8/15","1911",null,null,"N/A",null,null,null,false, false, false),
	new Project(240,"USA-FL-Orlando 3965 Silver Star Road - Lease Expiration","Analysis","CoStar  Webinar","Not Started",null,"Orlando","FL","United States","ACME CORPORATION, INC.","United States","1/8/15","1911",null,null,"N/A",null,null,null,false, false, false),
	new Project(241,"USA-CA-SF-One Embarcadero Ctr - Lease Expiration","Analysis","CoStar  Webinar","Not Started",null,"San Francisco","CA","United States","ACME CORPORATION, INC.","United States","1/8/15","1911",null,null,"N/A",null,"0",null,false, false, false),
	new Project(242,"USA-TX-Midland-Industrial Way - Lease Expiration","Analysis","CoStar  Webinar","Not Started",null,"Midland","TX","United States","ACME CORPORATION, INC.","United States","1/8/15","1911",null,null,"N/A",null,null,null,false, false, false),
	new Project(243,"USA-LA-Civington Northpark Corporate Center - Lease Expiration","Analysis","CoStar  Webinar","Not Started",null,"Covington","LA","United States","ACME CORPORATION, INC.","United States","1/8/15","1911",null,null,"N/A",null,null,null,false, false, false),
	new Project(244,"Acme Hospital - Lease Expiration","Analysis","CoStar  Webinar","Not Started",null,"Norfolk","VA","United States","ACME CORPORATION, INC.","United States","1/8/15","1911",null,null,"N/A",null,null,null,false, false, false),
	new Project(245,"Acme Hospital - Lease Expiration","Analysis","CoStar  Webinar","Not Started",null,"Norfolk","VA","United States","ACME CORPORATION, INC.","United States","1/8/15","1911",null,null,"N/A",null,null,null,false, false, false),
	new Project(246,"USA-CA- Santa Fe Springs - Lease Expiration","Analysis","CoStar  Webinar","Not Started",null,"Santa Fe Springs","CA","United States","ACME CORPORATION, INC.","United States","1/8/15","1911",null,null,"N/A",null,null,null,false, false, false),
	new Project(247,"Walmart - Lease Expiration","Analysis","CoStar  Webinar","Not Started",null,"Sparks","NV","United States","ACME CORPORATION, INC.","United States","1/8/15","1911",null,null,"N/A",null,null,null,false, false, false),
	new Project(248,"Walmart - Lease Expiration","Analysis","CoStar  Webinar","Not Started",null,"Sparks","NV","United States","ACME CORPORATION, INC.","United States","1/8/15","1911",null,null,"N/A",null,null,null,false, false, false),
	new Project(249,"USA-AL-Birmingham (Office) - Lease Expiration","Analysis","CoStar  Webinar","Not Started",null,"Birmingham","AL","United States","ACME CORPORATION, INC.","United States","1/8/15","1911",null,null,"N/A",null,null,null,false, false, false),
	new Project(250,"FIN-Helsinki-Melkonkatu (Office) - Contraction Notification End","Analysis","CoStar  Webinar","Not Started",null,"Helsinki",null,"Finland","ACME CORPORATION, INC.","Finland","1/8/15","1911",null,null,"N/A",null,null,null,false, false, false),
	new Project(251,"USA-GA-ATL-Lenox Towers North - ROFR/ROFO Notification End","Analysis","CoStar  Webinar","Not Started",null,"Atlanta","GA","United States","ACME CORPORATION, INC.","United States","1/8/15","1911",null,null,"N/A",null,"0",null,false, false, false),
	new Project(252,"Twelve Oaks Center - Lease Expiration","Construction","George Washington","Not Started",null,"Birmingham","AL","United States","RE Portfolio","United States","1/8/15","1911",null,null,"N/A",null,"0",null,false, false, false),
	new Project(253,"Overton Business Park - Lease Expiration","Analysis","George Washington","Not Started",null,"McLean","VA","United States","FASCO, Inc.","United States","1/8/15","1911",null,null,"N/A",null,null,null,false, false, false),
	new Project(254,"Muscogee Office Supply - Lease Expiration","Analysis","George Washington","Not Started",null,"Sarasota","FL","United States","FASCO, Inc.","United States","1/8/15","1911",null,null,"N/A",null,"0",null,false, false, false),
	new Project(255,"Muscogee Office Supply - Lease Expiration","Analysis","George Washington","Not Started",null,"Sarasota","FL","United States","FASCO, Inc.","United States","1/8/15","1911",null,null,"N/A",null,null,null,false, false, false),
	new Project(256,"El Paso Leasing and Supply - Lease Expiration","Analysis","George Washington","Not Started",null,null,null,null,"FASCO, Inc.",null,"1/8/15","1911",null,null,"N/A",null,null,null,false, false, false),
	new Project(257,"Acme Office Equipment - Lease Expiration","Analysis","George Washington","Not Started",null,null,null,null,"FASCO, Inc.","United States","1/8/15","1911",null,null,"N/A",null,null,null,false, false, false),
	new Project(258,"CAT Heavy Equipment - Lease Expiration","Analysis","George Washington","Not Started",null,null,null,null,"FASCO, Inc.",null,"1/8/15","1911",null,null,"N/A",null,null,null,false, false, false),
	new Project(259,"Acme Office Equipment - Lease Expiration","Analysis","George Washington","Not Started",null,null,null,null,"FASCO, Inc.","United States","1/8/15","1911",null,null,"N/A",null,null,null,false, false, false),
	new Project(260,"Acme Office Equipment - Lease Expiration","Analysis","George Washington","Not Started",null,null,null,null,"FASCO, Inc.","United States","1/8/15","1911",null,null,"N/A",null,null,null,false, false, false),
	new Project(261,"CAT Heavy Equipment - Lease Expiration","Analysis","George Washington","Not Started",null,null,null,null,"FASCO, Inc.",null,"1/8/15","1911",null,null,"N/A",null,null,null,false, false, false),
	new Project(262,"Muscogee Office Supply - Automatic Renewal Notification End","Analysis","George Washington","Not Started",null,"Sarasota","FL","United States","FASCO, Inc.","United States","1/8/15","1911",null,null,"N/A",null,null,null,false, false, false),
	new Project(264,"Relocation_DP","Relocation","John Hancock","Active","11/19/15","Parsippany","NJ","United States","RE Portfolio","United States","6/12/15","1756","-1596","12345","N/A","RE: 3) PHASE 3: NEGOTIATION Approved -  test.  Note Creator:  CoStar  Webinar","8",null,false, false, false),
	new Project(265,"Test Bob","Construction","Harriet Tubman","Active",null,null,"GA","United States","RE Portfolio",null,"8/4/15","1703",null,"5555","N/A",null,"0",null,false, false, false),
	new Project(269,"PMG 01","Construction","Ben Franklin","Active",null,null,null,null,"RE Portfolio",null,"9/1/15","1675",null,null,"N/A",null,"0",null,false, false, false),
	new Project(284,"PG 1","Analysis","CoStar  Webinar","Active","3/5/18",null,null,null,"CoStar Real Estate Manager - (Group)",null,"1/14/16","1540","-759",null,"N/A",null,"0",null,false, false, false),
	new Project(289,"Phipps Remodel","Construction","CoStar  Webinar","Active","9/29/17","Atlanta","AK","United States","CoStar Real Estate Manager - (Group)","United States","2/20/16","1503","-916",null,"N/A","RE: 1) Definition of Requirements Approved -  Approved.  Note Creator:  Abigail Adams","7",null,false, false, false),
	new Project(299,"TEST 123","Analysis","Evan Test","Active","9/28/17",null,"GA","United States","CoStar Real Estate Manager - (Group)",null,"5/20/16","1413","-917","55555","N/A",null,"0",null,false, false, false),
	new Project(307,"Sample Phase closeout","Construction","CoStar  Webinar","Active","8/7/16",null,"CO","United States","CoStar Real Estate Manager - (Group)",null,"8/4/16","1337","-1334",null,"N/A","RE: 2.2) sub 2 Approved -  Approved.  Note Creator:  CoStar  Webinar","57",null,false, false, false),
	new Project(309,"Atlanta Warehouse 001","Analysis","daniel galenkamp","Active",null,null,"GA","United States","CoStar Real Estate Manager - (Group)",null,"8/16/16","1325",null,null,"N/A","RE: 1) First Approved -  5.  Note Creator:  CoStar  Webinar","0",null,false, false, false),
	new Project(310,"Test User Experience for CS Manager","Construction","CoStar  Webinar","Active","8/17/18","Atlanta","GA","United States","CoStar Real Estate Manager - (Group)","United States","10/7/16","1273","-594","20test16","N/A","RE: 10) PHASE 9:  Documentation Approved -  Approved.  Note Creator:  CoStar  Webinar","18",null,false, false, false),
	new Project(315,"BD Test","Analysis","CoStar  Webinar","Active",null,null,"AR","United States","CoStar Real Estate Manager - (Group)",null,"1/12/17","1176",null,null,"N/A",null,null,null,false, false, false),
	new Project(316,"tester","Construction","Barbara E","Active",null,null,null,"United States","RE Portfolio",null,"1/24/17","1164",null,"123","N/A",null,"0",null,false, false, false),
	new Project(317,"test mw","Analysis","CoStar  Webinar","Active",null,null,"AL","United States","RE Portfolio",null,"4/25/17","1073",null,null,"N/A",null,null,null,false, false, false),
	new Project(320,"construction","Analysis","CoStar  Webinar","Active",null,null,"GA","United States","RE Portfolio",null,"8/1/17","975",null,null,"N/A","RE: 1) PHASE 0: Design / Project Approval Approved -  sddsfd.  Note Creator:  CoStar  Webinar","18",null,false, false, false),
	new Project(325,"test pg notes 1","Analysis","CoStar  Webinar","Active","3/5/18",null,null,null,"CoStar Real Estate Manager - (Group)",null,"1/14/16","1540","-759",null,"N/A",null,"0",null,false, false, false),
	new Project(326,"test pg notes 2","Analysis","CoStar  Webinar","Active","3/5/18",null,null,null,"CoStar Real Estate Manager - (Group)",null,"1/14/16","1540","-759",null,"N/A",null,"0",null,false, false, false),
	new Project(327,"test pg notes 3","Analysis","CoStar  Webinar","Active","1/18/16",null,null,null,"CoStar Real Estate Manager - (Group)",null,"1/14/16","1540","-1536",null,"N/A",null,"0",null,false, false, false),
	new Project(330,"Test Project","New Lease","CoStar  Webinar","Active",null,null,null,"United States","RE Portfolio",null,"1/3/18","820",null,null,"N/A",null,"0",null,false, false, false),
	new Project(334,"Atlanta-Hartsfiel Renewal","Renew","CoStar  Webinar","Active","6/20/18","Atlanta","GA","United States","RE Portfolio","United States","3/1/18","763","-652","ATL-Renew","N/A","RE: 5) Enter Instructions into Transaction Database (WIP) Approved -  approved.  Note Creator:  CoStar  Webinar","5",null,false, false, false),
	new Project(335,"ATL Hartsfield Renewal","Renew","CoStar  Webinar","Active","3/2/18","Atlanta","GA","United States","RE Portfolio","United States","3/1/18","763","-762","ATL-Renew","N/A",null,"0",null,false, false, false),
	new Project(338,"CoStar SDC Templates","Analysis","CoStar  Webinar","Active",null,null,null,"United States","RE Portfolio",null,"4/12/18","721",null,null,"N/A",null,null,null,false, false, false),
	new Project(339,"TJ BASELINE test","Site Close","CoStar  Webinar","Active","10/23/14",null,"ON","Canada","RE Portfolio",null,"9/15/13","2391","-1988",null,"N/A",null,"0",null,false, false, false),
	new Project(340,"Temporary Project","Extend","John Hancock","Active",null,null,"WA","United States","RE Portfolio",null,"5/3/18","700",null,"CHANDRA","N/A",null,"0",null,false, false, false),
	new Project(341,"Test 55","Site Close","CoStar  Webinar","Active",null,"Washington","DC","United States","RE Portfolio","United States","5/16/18","687",null,"55","N/A",null,null,null,false, false, false),
	new Project(342,"test 55","Site Close","CoStar  Webinar","Active",null,null,"DE","United States","RE Portfolio",null,"5/16/18","687",null,"555","N/A",null,null,null,false, false, false),
	new Project(343,"Test 200","Site Close","CoStar  Webinar","Active",null,null,"GA","United States","RE Portfolio",null,"5/16/18","687",null,null,"N/A",null,"0",null,false, false, false),
	new Project(344,"Test 201","Site Close","CoStar  Webinar","Active",null,"San Francisco","CA","United States","RE Portfolio","United States","5/16/18","687",null,"TEST201","N/A",null,null,null,false, false, false),
	new Project(345,"TEST100","Analysis","CoStar  Webinar","Active",null,null,"GA","United States","RE Portfolio",null,"5/21/18","682",null,null,"N/A",null,null,null,false, false, false),
	new Project(347,"TJ TEST Project 820","Construction","CoStar  Webinar","Active","12/19/19",null,"GA","United States","RE Portfolio",null,"8/20/18","591","-105","TempNOTJ","N/A",null,"9",null,false, false, false),
	new Project(348,"TEST","Construction","CoStar  Webinar","Active",null,null,"AR","United States","RE Portfolio",null,"8/8/05","5351",null,"123","N/A",null,"0",null,false, false, false),
	new Project(349,"Scott","Site Close","CoStar  Webinar","Active",null,null,null,"United States","ACME CORPORATION, INC.",null,"1/1/10","3744",null,null,"N/A",null,null,null,false, false, false),
	new Project(350,"Project Test 1","Analysis","CoStar  Webinar","Active",null,"Kennesaw","GA","United States","RE Portfolio","United States","11/1/18","518",null,"12345","N/A",null,null,null,false, false, false),
	new Project(351,"Project Test 2","Analysis","CoStar  Webinar","Active",null,"Norfolk","GA","United States","RE Portfolio","United States","11/2/18","517",null,"12345","N/A",null,null,null,false, false, false),
	new Project(352,"Project Test 3","Analysis","CoStar  Webinar","Active",null,"Rochester","GA","United States","RE Portfolio","United States","11/3/18","516",null,"12345","N/A",null,null,null,false, false, false),
	new Project(353,"Project Test 4","Analysis","CoStar  Webinar","Active",null,"Atlanta","GA","United States","RE Portfolio","United States","11/4/18","515",null,"12345","N/A",null,null,null,false, false, false),
	new Project(354,"Project Test 5","Analysis","CoStar  Webinar","Active",null,"Tallahassee","GA","United States","RE Portfolio","United States","11/5/18","514",null,"12345","N/A",null,null,null,false, false, false),
	new Project(355,"Project Test 6","Analysis","CoStar  Webinar","Active",null,"Atlanta","GA","United States","RE Portfolio","United States","11/6/18","513",null,"12345","N/A",null,null,null,false, false, false),
	new Project(356,"Project Test 7","Analysis","CoStar  Webinar","Active",null,"San Francisco","GA","United States","RE Portfolio","United States","11/7/18","512",null,"12345","N/A",null,null,null,false, false, false),
	new Project(357,"Project Test 8","Analysis","CoStar  Webinar","Active",null,"San Francisco","GA","United States","RE Portfolio","United States","11/8/18","511",null,"12345","N/A",null,null,null,false, false, false),
	new Project(358,"Project Test 9","Analysis","CoStar  Webinar","Active",null,"Atlanta","GA","United States","RE Portfolio","United States","11/9/18","510",null,"12345","N/A",null,null,null,false, false, false),
	new Project(359,"Project Test 10","Analysis","CoStar  Webinar","Active",null,"Example Town","GA","United States","RE Portfolio","United States","11/10/18","509",null,"12345","N/A",null,null,null,false, false, false),
	new Project(361,"rahul test project","Construction","CoStar  Webinar","Active",null,null,null,"United States","RE Portfolio",null,"1/25/19","433",null,"3321","N/A",null,"0",null,false, false, false),
	new Project(370,"CA, LOS ANGELES - New Lease","New Lease","CoStar  Webinar","Active","7/3/19","El Segundo","CA","United States","HS","United States","2/13/19","414","-274","123486","Waiting on LL to provide up detail","RE: 4) Scope Concurrence Approved -  test.  Note Creator:  Debra Haufler","21",null,false, false, false),
	new Project(371,"Demo Project 1","Construction","John Hancock","Active",null,"Atlanta","GA","United States","RE Portfolio","United States","2/20/19","407",null,"12345XYZ","N/A",null,"0",null,false, false, false),
	new Project(372,"Test BG 1","New Lease","CoStar  Webinar","Active","3/25/19",null,"GA","United States","RE Portfolio",null,"3/11/19","388","-374","TEST Lonza Project 99","N/A",null,"0",null,false, false, false),
	new Project(374,"Christie Gaddy","Relocation","Cheri Smith","Active","9/24/19",null,"NC","United States","BioMed",null,"3/12/19","387","-191",null,"N/A",null,"0",null,false, false, false),
	new Project(375,"ABC","Reconfiguration","Cheri Smith","Active","9/27/19","San Francisco","CA","United States","RE Portfolio","United States","3/15/19","384","-188","12345","N/A",null,null,null,false, false, false),
	new Project(376,"NewSiteTEST","Analysis","Dana Davis","Active","10/14/19","Charlotte","NC","United States","American Broker Company","United States","4/1/19","367","-171","123456","N/A",null,"0",null,false, false, false),
	new Project(377,"Rahul","Infrastructure","CoStar  Webinar","Active",null,null,null,"United States","RE Portfolio",null,"5/13/19","325",null,null,"N/A",null,null,null,false, false, false),
	new Project(378,"Test","Analysis","CoStar  Webinar","Active",null,null,null,"United States","RE Portfolio",null,"5/1/19","337",null,null,"N/A",null,null,null,false, false, false),
	new Project(380,"Training Project","Analysis","CoStar  Webinar","Active","7/9/20",null,"GA","United States","RE Portfolio",null,"8/1/19","245","98","2222","N/A","RE: 1.1) Review Critical Date Report Approved -  This is a note for approval of task 1.1.  Note Creator:  CoStar  Webinar","0",null,false, false, false),
	new Project(381,"Phipps Renewal","Renew","CoStar  Webinar","Active",null,"Atlanta","GA","United States","RE Portfolio","United States","8/29/19","217",null,null,"N/A",null,null,null,false, false, false),
	new Project(382,"Renewal Phipps","Renew","CoStar  Webinar","Active",null,"Atlanta","GA","United States","Able Engineering Services","United States","8/29/19","217",null,"riskconnectID","N/A",null,null,null,false, false, false),
	new Project(384,"BuildingNameTest","Renew","CoStar  Webinar","Active",null,null,null,"United States","Able Engineering Services",null,"9/26/19","189",null,null,"N/A",null,null,null,false, false, false),
	new Project(385,"mjdtest","Analysis","CoStar  Webinar","Active","11/8/19",null,"FL","United States","Able Engineering Services",null,"10/11/19","174","-146",null,"N/A",null,"0",null,false, false, false),
	new Project(386,"test","Construction","CoStar  Webinar","Active",null,null,null,"United States","Able Engineering Services",null,"10/25/19","160",null,null,"N/A",null,"0",null,false, false, false),
	new Project(387,"Test","Analysis","CoStar  Webinar","Active",null,"Atlanta","GA","United States","RE Portfolio","United States","11/25/19","129",null,"Test_CoStar12345","N/A",null,"0",null,false, false, false),
	new Project(388,"Test","Analysis","CoStar  Webinar","Active",null,null,"GA","United States","Able Engineering Services",null,"11/25/19","129",null,null,"N/A",null,"0",null,false, false, false),
	new Project(389,"test","Analysis","CoStar  Webinar","Active",null,null,null,"United States","Able Engineering Services",null,"12/5/19","119",null,null,"N/A",null,null,null,false, false, false),
	new Project(390,"RE Lease Renew","Renew","CoStar  Webinar","Active",null,"Atlanta","GA","United States","ACME CORPORATION, INC.","United States","1/9/20","84",null,null,"N/A",null,"0",null,false, false, false),
	new Project(391,"Project Equipment Renew","Renew","CoStar  Webinar","Active",null,"Twinsburg","OH","United States","ACME CORPORATION, INC.","United States","1/9/20","84",null,null,"N/A",null,"0",null,false, false, false),
	new Project(392,"c k","Renew","CoStar  Webinar","Active",null,null,"GA","United States","BioMed",null,"1/13/20","80",null,null,"N/A",null,"0",null,false, false, false),
	new Project(393,"TEST 2","Renew","CoStar  Webinar","Active",null,null,"OH","United States","ACME CORPORATION, INC.",null,"1/16/20","77",null,null,"N/A",null,"0",null,false, false, false),
	new Project(394,"Test Project","Renew","CoStar  Webinar","Active",null,"Sarasota","FL","United States","FASCO, Inc","United States","1/16/20","77",null,null,"N/A",null,"0",null,false, false, false),
	new Project(395,"c k","Renew","CoStar  Webinar","Active",null,"Indianapolis","GA","United States","Able Engineering Services","United States","1/16/20","77",null,null,"N/A",null,"0",null,false, false, false),
	new Project(396,"Test","New Lease","CoStar  Webinar","Active",null,null,"AL","United States","Able Engineering Services",null,"1/23/20","70",null,null,"N/A",null,null,null,false, false, false),
	new Project(397,"New BS Project","New Lease","John Hancock","Active","1/6/21",null,"GA","United States","ACME CORPORATION, INC.",null,"1/29/20","64","279",null,"N/A",null,"0",null,false, false, false),
	new Project(402,"CGC Training 2","Construction","CoStar  Webinar","Active","5/4/21",null,"CO","United States","Able Engineering Services",null,"3/3/20","30","397",null,"N/A",null,"0",null,false, false, false),
	new Project(403,"AR TEST PROJECT","Analysis","CoStar  Webinar","Active",null,null,"GA","United States","Able Engineering Services",null,"3/4/20","29",null,null,"N/A","RE: 1) Task 1 Approved -  test.  Note Creator:  CoStar  Webinar","17",null,false, false, false),
	new Project(404,"Test","New Lease","CoStar  Webinar","Active",null,null,"GA","United States","ACME CORPORATION, INC.",null,"3/6/20","27",null,"Test2","N/A",null,null,null,false, false, false),
	new Project(405,"Cool Project","New Lease","CoStar  Webinar","Active",null,null,null,"United States","RE Portfolio",null,"3/6/20","27",null,null,"N/A",null,"0",null,false, false, false),
];
