using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.IdentityModel.Tokens.Jwt;
using System.Net.Http;
using System.Net.Http.Json;
using System.Security.Claims;
using System.Threading.Tasks;

namespace Mango.MangoSPA.Server.Controllers;

public record AccessTokenRequest
{
    // Required - value must be: authorization_code
    public string GrantType { get; set; }

    // Required - authorization_code that was generated by the /authorize endpoint. 
    // Short lived (10 min) and should NOT be used more than once
    public string Code { get; set; }

    // Required - client URI
    public string RedirectUri { get; set; }

    // Required - the raw code_verifier (PKCE) value that was generated by the client
    public string CodeVerifier { get; set; }
}

public record AccessTokenResponse
{
    public string AccessToken { get; set; }
    public string TokenType { get; set; }
}

public class AccountController : ControllerBase
{
    readonly IHttpClientFactory _clientFactory;

    public AccountController(IHttpClientFactory clientFactory)
    {
        _clientFactory = clientFactory;
    }

    /// <summary>
    /// Calls Identity API which generates an accessToken (JWT) using the current logged in user's claims
    /// Then creates an http-only cookie to keep the user logged-in
    /// </summary>
    /// <param name="request"></param>
    /// <returns></returns>
    [HttpPost("~/oauth/token")] //oauth/token   
    [ProducesResponseType(StatusCodes.Status401Unauthorized)]
    [ProducesResponseType(StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status500InternalServerError)]
    public async Task<ActionResult<AccessTokenResponse>> Token([FromBody] AccessTokenRequest request)
    {
        var client = _clientFactory.CreateClient("identity-api");

        var response = await client.PostAsJsonAsync("oauth/token", request);
        if (!response.IsSuccessStatusCode)
        {
            var error = await response.Content.ReadAsStringAsync();
            return Unauthorized(error);
        }

        var result = await response.Content.ReadFromJsonAsync<AccessTokenResponse>();

        JwtSecurityToken token = new JwtSecurityTokenHandler().ReadJwtToken(result.AccessToken);
        var userIdentity = new ClaimsIdentity(token.Claims, CookieAuthenticationDefaults.AuthenticationScheme);
        var userPrincipal = new ClaimsPrincipal(userIdentity);

        await HttpContext.SignInAsync(userPrincipal, 
            new AuthenticationProperties
            {
                ExpiresUtc = token.ValidTo
            });

        return Ok(result);
    }

    [HttpPost("logout")] //account/logout   
    [ProducesResponseType(StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status500InternalServerError)]
    public async Task<ActionResult> Logout()
    {
        await HttpContext.SignOutAsync();
        return LocalRedirect(Url.Content("~/"));
    }
}

