namespace MangoSPA.Models;

//public record LoginRequest(string Email, string Password, string ClientKey = "");
//public record LoginResponse(string AuthToken, string Email, bool HasMultipleSites, string ClientKey);
//public record LoginToClientRequest(string ClientKey, int ContactId, string ContactRole, bool? IsDefaultLoginContact, int DefaultLoginContactId);
//public record LoginToClientResponse(string AuthToken);


public record AccessTokenRequest
{
    // Required - value must be: authorization_code
    public string GrantType { get; set; }

    // Required - authorization_code that was generated by the /authorize endpoint. 
    // Short lived (10 min) and should NOT be used more than once
    public string Code { get; set; }

    // Required - client URI
    public string RedirectUri { get; set; }

    // Required - the raw code_verifier (PKCE) value that was generated by the client
    public string CodeVerifier { get; set; }

    // Non-OAuth specific param
    // If source=v06, that means we came from V06 and V06 is already logged in.
    // Therefore, there is no need to generate a new auth code for V06
    public string Source { get; set; }
}

public record AccessTokenResponse
{
    public string AccessToken { get; set; }
    public string TokenType { get; set; }
}

//public class AuthorizeRequest
//{
//    // Required - Value must be 'code'
//    public string ResponseType { get; set; }

//    // Required - Must be 'mango-spa' or 'crem'
//    public string ClientId { get; set; }

//    // Required - Client generates this. The encrypted value of a code_verifier (PKCE).
//    public string CodeChallenge { get; set; }

//    // Optional - Client specifies this. The algorithm used to encrypt the code_verifier. Value must be 'S256' which is the default algorithm we are using currently.
//    public string CodeChallengMethod { get; set; }

//    // Required - Client Uri
//    public string RedirectUri { get; set; }

//    // Optional
//    public string Scope { get; set; }

//    // Optional
//    public string State { get; set; }
//}

public record AuthorizeResponse
{
    public string Code { get; set; }
    public string RedirectUri { get; set; }
    public string State { get; set; }
    public string Issuer { get; set; }
}

public record OAuthResponse
{
    public string AccessToken { get; set; }
    public string Code { get; set; }
    public string RedirectUri { get; set; }
}

// Current user
public record AuthenticatedUser
{
    public int UserId { get; set; }
    public string Email { get; set; }
    public string Role { get; set; }
    public string ClientKey { get; set; }
    public int ContactId { get; set; }
    public string ContactRole { get; set; }
    public bool IsAutoProvisioned { get; set; }
    public bool IsRemUser { get; set; }
}

public record UserAuthSession
{
    public string SessionId { get; set; }
    public AuthenticatedUser User { get; set; }
    public DateTimeOffset? ExpiresUtc { get; set; }
    public string OS { get; set; }
    public string Browser { get; set; }

    //public DateTimeOffset? LastActivity { get; set; }
}

public record AuthSessionResponse
{
    public int Total { get; set; }
    public List<UserAuthSession> Data { get; set; }
}