namespace MangoSPA.Models;

public record LoginRequest(string Email, string Password, string ClientKey = "");
public record LoginResponse(string AuthToken, string Email, bool HasMultipleSites, string ClientKey);
public record LoginToClientRequest(string ClientKey, int ContactId, string ContactRole, bool? IsDefaultLoginContact, int DefaultLoginContactId);
public record LoginToClientResponse(string AuthToken);


public record AccessTokenRequest
{
    // Required - value must be: authorization_code
    public string GrantType { get; set; }

    // Required - authorization_code that was generated by the /authorize endpoint. 
    // Short lived (10 min) and should NOT be used more than once
    public string Code { get; set; }

    // Required - client URI
    public string RedirectUri { get; set; }

    // Required - the raw code_verifier (PKCE) value that was generated by the client
    public string CodeVerifier { get; set; }
}

public record AccessTokenResponse
{
    public string AccessToken { get; set; }
    public string TokenType { get; set; }
}